Repository exercism/go, pull requests merged in 2021-10, with the labels that each got.

#1726 Improve party-robot hints.md (#1588)
  exercises/concept/party-robot/.docs/hints.md
Labels: status/awaiting-contributor

#1735 `cars-assemble`: simplify the type conversion intro
  exercises/concept/cars-assemble/.docs/introduction.md
Labels: x:size/small, september-sprint, status/awaiting-maintainer

#1739 savings-account: change status to `wip`
  config.json
Labels: x:size/tiny

#1744 Add out-of-bounds to `card-tricks` instructions
  exercises/concept/card-tricks/.docs/instructions.md
Labels: september-sprint, status/awaiting-contributor

#1707 logs-logs-logs: update concept and exercise content
  concepts/runes/.meta/config.json
  concepts/runes/about.md
  concepts/runes/introduction.md
  concepts/runes/links.json
  exercises/concept/logs-logs-logs/.docs/hints.md
  exercises/concept/logs-logs-logs/.docs/instructions.md
  exercises/concept/logs-logs-logs/.docs/introduction.md
  exercises/concept/logs-logs-logs/.meta/config.json
  exercises/concept/logs-logs-logs/.meta/design.md
  exercises/concept/logs-logs-logs/.meta/exemplar.go
  exercises/concept/logs-logs-logs/logs.go
  exercises/concept/logs-logs-logs/logs_test.go
Labels: x:size/large, status/awaiting-contributor

#1753 Fix `weather-forecast` task 1 hints not showing up
  exercises/concept/weather-forecast/.docs/hints.md
Labels: x:size/tiny

#1754 Add a hint to `cars-assemble` task 2 about casting
  exercises/concept/cars-assemble/.docs/hints.md
Labels: x:size/tiny, hacktoberfest-accepted

#1764 Add some basic hints to cars-assemble.
  exercises/concept/cars-assemble/.docs/hints.md
Labels: x:size/small

#1768 election-day: Fix TestNewElectionResult
  exercises/concept/election-day/election_day_test.go
Labels: x:size/small

#1760 Weather forecast: Remove non-SI unit from examples
  exercises/concept/weather-forecast/.docs/introduction.md
Labels: x:size/tiny

#1770 lasagna-master: fix missing link and add a new one on hints
  exercises/concept/lasagna-master/.docs/hints.md
Labels: x:size/small, status/awaiting-contributor

#1773 Fix function names in lasagna-master; tweak language slightly
  exercises/concept/lasagna-master/.docs/instructions.md
Labels: x:size/small

#1758 Remove references to exercises from concept docs.
  concepts/basics/about.md
  concepts/basics/introduction.md
  concepts/comments/about.md
  concepts/comments/introduction.md
  concepts/numbers/about.md
  concepts/numbers/introduction.md
  concepts/pointers/about.md
  concepts/pointers/introduction.md
  concepts/range-iteration/introduction.md
  concepts/time/about.md
Labels: x:size/small, status/awaiting-maintainer

#1777 booking-up-for-beauty: add booleans to prerequisites
  config.json
  exercises/concept/booking-up-for-beauty/.meta/design.md
Labels: x:size/tiny

#1737 Fill out the `interfaces` concept
  concepts/interfaces/.meta/config.json
  concepts/interfaces/about.md
  concepts/interfaces/introduction.md
  concepts/interfaces/links.json
Labels: september-sprint, status/awaiting-contributor

#1778 Add pointers, range-iteration and functions prerequisites to exercises
  config.json
  exercises/concept/census/.meta/design.md
  exercises/concept/gross-store/.meta/design.md
  exercises/concept/logs-logs-logs/.meta/design.md
Labels: x:size/small

#1772 Grammar: replace comma with an idea connector (concepts/functions)
  concepts/functions/about.md
  concepts/functions/introduction.md
  exercises/concept/lasagna-master/.docs/introduction.md
Labels: x:size/tiny, status/awaiting-contributor

#1765 Update party robot introduction
  concepts/packages/about.md
  concepts/packages/introduction.md
  concepts/structs/about.md
  exercises/concept/party-robot/.docs/introduction.md
Labels: x:size/small, status/awaiting-contributor

#1779 Grammar and word smithing: maps and gross-store
  concepts/maps/about.md
  concepts/maps/introduction.md
  exercises/concept/gross-store/.docs/instructions.md
  exercises/concept/gross-store/.docs/introduction.md
  exercises/concept/gross-store/gross_store.go
Labels: x:size/small, status/awaiting-contributor

#1781 election-day: fix typos
  exercises/concept/election-day/.docs/instructions.md
  exercises/concept/election-day/.meta/config.json
Labels: x:size/tiny

#1780 Fix typos in `logs-logs-logs` exercise docs
  concepts/runes/about.md
  concepts/runes/introduction.md
  exercises/concept/logs-logs-logs/.docs/instructions.md
  exercises/concept/logs-logs-logs/.docs/introduction.md
Labels: x:size/tiny

#1752 cars-assemble: explain and use the `if expression; condition { }` syntax
  concepts/conditionals-if/about.md
  concepts/conditionals-if/introduction.md
  exercises/concept/cars-assemble/.docs/hints.md
  exercises/concept/cars-assemble/.docs/instructions.md
  exercises/concept/cars-assemble/.docs/introduction.md
  exercises/concept/cars-assemble/.meta/exemplar.go
  exercises/concept/cars-assemble/cars_assemble.go
  exercises/concept/cars-assemble/cars_assemble_test.go
Labels: september-sprint, status/awaiting-contributor

#1774 triangle: remove degenerate triangle test cases
  exercises/practice/triangle/triangle_test.go
Labels: x:size/small, status/awaiting-maintainer

#1762 Fix instructions for this problem to suggest returning an error.
  exercises/practice/hamming/.docs/instructions.md
Labels: x:size/small, status/awaiting-maintainer

#1783 Word smithing for concept range
  concepts/range-iteration/about.md
  concepts/range-iteration/introduction.md
  exercises/concept/chessboard/.docs/introduction.md
Labels: x:size/small

#1785 Fix census.go package doc to pass go lint
  exercises/concept/census/.meta/exemplar.go
  exercises/concept/census/census.go
Labels: x:size/tiny, status/awaiting-contributor

#1747 Docs(concept-methods): update code block to have correct formatting
  concepts/methods/about.md
  concepts/methods/introduction.md
Labels: x:size/tiny, status/awaiting-contributor, hacktoberfest-accepted

#1795 Fix typo
  exercises/concept/need-for-speed/.docs/instructions.md
Labels: x:size/tiny

#1766 Cleanups for Lasagna exercise and basics concept from feedback.
  concepts/basics/about.md
  concepts/basics/introduction.md
  exercises/concept/lasagna/.docs/hints.md
  exercises/concept/lasagna/.docs/instructions.md
  exercises/concept/lasagna/.docs/introduction.md
  exercises/concept/lasagna/.meta/config.json
  exercises/concept/lasagna/lasagna.go
Labels: x:size/medium, status/awaiting-maintainer

#1805 Improve instructions for AnniversaryDate
  exercises/concept/booking-up-for-beauty/.docs/hints.md
  exercises/concept/booking-up-for-beauty/.docs/instructions.md
Labels: x:size/tiny

#1807 Update instructions.md
  exercises/concept/lasagna-master/.docs/instructions.md
Labels: x:size/tiny

#1798 Improve language
  exercises/concept/party-robot/.meta/exemplar.go
  exercises/concept/party-robot/party_robot.go
Labels: x:size/tiny, status/awaiting-contributor

#1800 fix: removed doubled up wording in exercises
  concepts/pointers/about.md
  concepts/pointers/introduction.md
  exercises/concept/election-day/.docs/introduction.md
Labels: x:size/tiny, status/awaiting-maintainer

#1919 Fix typo in PR commenter template
  .github/pr-commenter.yml
Labels: x:size/tiny

#1917 Add stub functions to practice exercises M-P
  exercises/practice/matching-brackets/matching_brackets.go
  exercises/practice/matrix/matrix.go
  exercises/practice/matrix/matrix_test.go
  exercises/practice/meetup/meetup.go
  exercises/practice/meetup/meetup_test.go
  exercises/practice/minesweeper/minesweeper.go
  exercises/practice/ocr-numbers/.docs/instructions.append.md
  exercises/practice/ocr-numbers/ocr_numbers.go
  exercises/practice/ocr-numbers/ocr_numbers_test.go
  exercises/practice/paasio/paasio.go
  exercises/practice/palindrome-products/palindrome_products.go
  exercises/practice/palindrome-products/palindrome_products_test.go
  exercises/practice/pangram/pangram.go
  exercises/practice/pascals-triangle/pascals_triangle.go
  exercises/practice/perfect-numbers/perfect_numbers.go
  exercises/practice/phone-number/phone_number.go
  exercises/practice/pig-latin/pig_latin.go
  exercises/practice/poker/poker.go
  exercises/practice/poker/poker_test.go
  exercises/practice/pov/.docs/instructions.append.md
  exercises/practice/pov/pov.go
  exercises/practice/pov/pov_test.go
  exercises/practice/prime-factors/prime_factors.go
  exercises/practice/protein-translation/protein_translation.go
  exercises/practice/pythagorean-triplet/pythagorean_triplet.go
  exercises/practice/pythagorean-triplet/pythagorean_triplet_test.go
Labels: x:size/medium, status/awaiting-contributor, hacktoberfest-accepted

#1916 Update scrabble_score.go
  exercises/practice/scrabble-score/scrabble_score.go
Labels: x:size/tiny, status/awaiting-contributor, hacktoberfest-accepted

#1775 bird-watcher: add "for loop" concept
  concepts/for-loops/.meta/config.json
  concepts/for-loops/about.md
  concepts/for-loops/introduction.md
  concepts/for-loops/links.json
  config.json
  exercises/concept/bird-watcher/.docs/hints.md
  exercises/concept/bird-watcher/.docs/instructions.md
  exercises/concept/bird-watcher/.docs/introduction.md
  exercises/concept/bird-watcher/.meta/config.json
  exercises/concept/bird-watcher/.meta/exemplar.go
  exercises/concept/bird-watcher/bird_watcher.go
  exercises/concept/bird-watcher/bird_watcher_test.go
  exercises/concept/bird-watcher/go.mod
Labels: x:size/large, status/awaiting-contributor, hacktoberfest-accepted
