Repository exercism/go, pull requests merged in 2021-12, with the labels that each got.

#1977 Non-zero values returned wit non-zero errors
  exercises/practice/protein-translation/.meta/example.go
  exercises/practice/protein-translation/protein_translation_test.go
Labels: x:size/small, status/awaiting-contributor

#1978 Update instructions.md
  exercises/concept/weather-forecast/.docs/instructions.md
Labels: x:size/small

#1979 Wrapped CalculateResellPrice under Test.Run
  exercises/concept/vehicle-purchase/vehicle_purchase_test.go
Labels: x:size/small

#1980 List Ops: undefined func
  exercises/practice/list-ops/.meta/example.go
  exercises/practice/list-ops/list_ops.go
  exercises/practice/list-ops/list_ops_test.go
Labels: x:size/small

#1982 Instructions for missed case in PrefilledSlice
  exercises/concept/card-tricks/.docs/instructions.md
Labels: x:size/small

#1976 the-farm: teach about interfaces
  concepts/errors/introduction.md
  config.json
  exercises/concept/the-farm/.docs/hints.md
  exercises/concept/the-farm/.docs/instructions.md
  exercises/concept/the-farm/.docs/introduction.md
  exercises/concept/the-farm/.meta/config.json
  exercises/concept/the-farm/.meta/exemplar.go
  exercises/concept/the-farm/the_farm.go
  exercises/concept/the-farm/the_farm_test.go
  exercises/concept/the-farm/the_farm_types.go
Labels: x:size/medium, status/awaiting-maintainer

#1983 Updates for the-farm and errors concept
  concepts/error-handling/about.md
  concepts/error-handling/introduction.md
  concepts/error-wrapping/.meta/config.json
  concepts/error-wrapping/about.md
  concepts/error-wrapping/introduction.md
  concepts/error-wrapping/links.json
  concepts/errors/.meta/config.json
  concepts/errors/about.md
  concepts/errors/introduction.md
  concepts/errors/links.json
  config.json
  exercises/concept/the-farm/.docs/hints.md
  exercises/concept/the-farm/.docs/instructions.md
  exercises/concept/the-farm/.docs/introduction.md
  exercises/concept/the-farm/.meta/config.json
  exercises/concept/the-farm/.meta/design.md
  exercises/concept/the-farm/.meta/exemplar.go
  exercises/concept/the-farm/the_farm.go
  exercises/concept/the-farm/the_farm_test.go
  exercises/concept/the-farm/the_farm_types.go
  exercises/concept/the-farm/types.go
Labels: x:size/medium

#1981 Pythagorean triplets exercise could use more detailed explanation
  exercises/practice/pythagorean-triplet/.docs/instructions.append.md
  exercises/practice/pythagorean-triplet/pythagorean_triplet.go
Labels: x:size/small

#1988 Fixed link reference text
  concepts/functions/about.md
Labels: x:size/tiny

#1992 Add test to the_farm.go
  exercises/concept/the-farm/the_farm_test.go
Labels: x:size/small

#1993 Consistent naming for ErrScaleMalfunction
  exercises/concept/the-farm/.docs/instructions.md
  exercises/concept/the-farm/the_farm_test.go
Labels: x:size/tiny

#1991 add missing prerequisite for chessboard
  config.json
  exercises/concept/chessboard/.meta/design.md
Labels: x:size/tiny

#1994 Included TimeZone in AnniversaryDate Instructions
  exercises/concept/booking-up-for-beauty/.docs/instructions.md
Labels: x:size/tiny

#1996 Check explicit zero-value for street key
  exercises/concept/census/census_test.go
Labels: x:size/small

#1999 Make roadmap available on the website
  docs/ROADMAP.md
  docs/config.json
Labels: x:size/small

#2001 Extended Instructions for AddItem Function
  exercises/concept/gross-store/.docs/instructions.md
Labels: x:size/small

#2005 Concept Errors: Add missing references to documentation
  concepts/errors/about.md
  concepts/errors/introduction.md
Labels: x:size/small

#2003 sorting-room: Align hints.md content to sorting_room.go source
  exercises/concept/sorting-room/.docs/hints.md
Labels: x:size/tiny

#2008 Add missing prerequisite for-loops for Lasagna Master
  config.json
  exercises/concept/lasagna-master/.meta/design.md
Labels: x:size/tiny

#2006 String Formatting and Packages: Syncronize concept docs, fix blurb etc
  concepts/packages/introduction.md
  concepts/string-formatting/.meta/config.json
  concepts/string-formatting/about.md
  concepts/string-formatting/introduction.md
  concepts/string-formatting/links.json
  exercises/concept/party-robot/.docs/introduction.md
Labels: x:size/small

#2010 Fixed typo in Errors concept and the farm exercise
  concepts/errors/about.md
  concepts/errors/introduction.md
  exercises/concept/the-farm/.docs/introduction.md
Labels: x:size/tiny

#2009 Instructions fix for The Farm
  exercises/concept/the-farm/.docs/instructions.md
Labels: x:size/small, status/awaiting-maintainer

#2012 list-ops: fix typo in stub function
  exercises/practice/list-ops/list_ops.go
Labels: x:size/tiny

#2017 Integer Test case added
  exercises/concept/sorting-room/sorting_room_test.go
Labels: x:size/small

#2024 sorting-room: fix test description typo
  exercises/concept/sorting-room/sorting_room_test.go
Labels: x:size/tiny

#2023 the-farm: fix go-staticcheck warning
  exercises/concept/the-farm/.docs/instructions.md
  exercises/concept/the-farm/.meta/exemplar.go
  exercises/concept/the-farm/the_farm_test.go
Labels: x:size/small

#2025 Atbash Cipher: Refine the exercise description
  exercises/practice/atbash-cipher/.docs/instructions.md
Labels: x:size/small

#2028 Update instructions.md
  exercises/concept/weather-forecast/.docs/instructions.md
Labels: x:size/small

#2030 Capitalized the language name
  exercises/concept/lasagna-master/.docs/introduction.md
Labels: x:size/tiny

#2026 Update sorting_room_test.go
  exercises/concept/sorting-room/sorting_room_test.go
Labels: x:size/small, status/awaiting-contributor

#2032 added test case for negative amount with non-scale error #2011
  exercises/concept/the-farm/the_farm_test.go
Labels: x:size/small

#2033 Add field names to structs when failing tests for Structs tutorial
  exercises/concept/need-for-speed/need_for_speed_test.go
Labels: x:size/small

#2031 Update design.md
  exercises/concept/need-for-speed/.meta/design.md
Labels: x:size/small

#2034 Capitalized the language name & typo fix
  concepts/maps/about.md
  concepts/maps/introduction.md
  exercises/concept/gross-store/.docs/introduction.md
Labels: x:size/tiny, status/awaiting-contributor

#2040 Correct typo in Chessboard exercise
  exercises/concept/chessboard/.meta/exemplar.go
  exercises/concept/chessboard/chessboard.go
Labels: x:size/tiny

#2039 More fixes to the "Go" word
  concepts/maps/about.md
Labels: x:size/tiny

#1971 cars-assemble: Rework to cover only numbers & arithmetic-operators
  exercises/concept/cars-assemble/.docs/hints.md
  exercises/concept/cars-assemble/.docs/instructions.md
  exercises/concept/cars-assemble/.docs/introduction.md
  exercises/concept/cars-assemble/.meta/config.json
  exercises/concept/cars-assemble/.meta/design.md
  exercises/concept/cars-assemble/.meta/exemplar.go
  exercises/concept/cars-assemble/cars_assemble.go
  exercises/concept/cars-assemble/cars_assemble_test.go
Labels: x:size/medium, status/awaiting-contributor

#2042 booking-up-for-beauty: fix instructions output for exercise 5
  exercises/concept/booking-up-for-beauty/.docs/instructions.md
Labels: x:size/small

#2044 Escape asterisks
  exercises/concept/cars-assemble/.docs/instructions.md
Labels: x:size/tiny

#2045 Fix broken link in nucleotide-count's description
  exercises/practice/nucleotide-count/.docs/instructions.append.md
Labels: x:size/tiny

#2048 Simplified Linked List Reverse
  exercises/practice/linked-list/.meta/example.go
Labels: x:size/small
