Repository exercism/go, pull requests merged in 2021-11, with the labels that each got.

#1922 Added quotes to strings
  exercises/practice/atbash-cipher/atbash_cipher_test.go
Labels: x:size/tiny

#1926 Deprecate exercise accumulate
  config.json
Labels: x:size/tiny

#1923 simple-linked-list: Add size test cases for Push and Pop methods
  exercises/practice/simple-linked-list/.meta/config.json
  exercises/practice/simple-linked-list/simple_linked_list_test.go
Labels: x:size/small

#1928 🤖 Remove obsolete `maintainers.json` file
  config/maintainers.json
Labels: x:size/tiny

#1935 Fix embedded mutex in `bank-account` example
  exercises/practice/bank-account/.meta/example.go
Labels: x:size/tiny

#1932 Fix Windows CI issue
  .github/workflows/exercise-tests.yml
Labels: x:size/tiny

#1921 Add stub functions to practice exercises Q-S
  exercises/practice/queen-attack/queen_attack.go
  exercises/practice/rail-fence-cipher/rail_fence_cipher.go
  exercises/practice/react/react.go
  exercises/practice/rectangles/rectangles.go
  exercises/practice/reverse-string/reverse_string.go
  exercises/practice/robot-name/robot_name.go
  exercises/practice/robot-simulator/.docs/instructions.append.md
  exercises/practice/robot-simulator/robot_simulator.go
  exercises/practice/robot-simulator/robot_simulator_step2_test.go
  exercises/practice/robot-simulator/robot_simulator_step3_test.go
  exercises/practice/robot-simulator/robot_simulator_test.go
  exercises/practice/roman-numerals/roman_numerals.go
  exercises/practice/rotational-cipher/rotational_cipher.go
  exercises/practice/run-length-encoding/run_length_encoding.go
  exercises/practice/saddle-points/saddle_points.go
  exercises/practice/say/say.go
  exercises/practice/scale-generator/scale_generator.go
  exercises/practice/secret-handshake/secret_handshake.go
  exercises/practice/series/series.go
  exercises/practice/series/series_test.go
  exercises/practice/sieve/sieve.go
  exercises/practice/simple-cipher/simple_cipher.go
  exercises/practice/simple-linked-list/simple_linked_list.go
  exercises/practice/simple-linked-list/simple_linked_list_test.go
  exercises/practice/spiral-matrix/spiral_matrix.go
  exercises/practice/strain/strain.go
  exercises/practice/strain/strain_test.go
  exercises/practice/sublist/sublist.go
  exercises/practice/sum-of-multiples/sum_of_multiples.go
Labels: x:size/medium

#1938 Pin version of golangci-lint and remove experimental checks
  .golangci.yml
  bin/fetch-golangci-lint
Labels: x:size/tiny

#1933 comments have sorted according to exercise order
  exercises/concept/elons-toys/.meta/exemplar.go
  exercises/concept/elons-toys/elons_toys.go
Labels: x:size/tiny

#1942 gross store: added test case for item added twice
  exercises/concept/gross-store/gross_store_test.go
Labels: x:size/small

#1943 phone-number: move go specific instruction to instructions.append.md (#1925)
  exercises/practice/phone-number/.docs/instructions.append.md
  exercises/practice/phone-number/.docs/instructions.md
Labels: x:size/small

#1944 Fix typo in concepts/pointers
  concepts/pointers/about.md
  concepts/pointers/introduction.md
  exercises/concept/election-day/.docs/introduction.md
Labels: x:size/tiny

#1945 Fix typo in exercises/concept/elons-toys/.docs/instructions.md
  exercises/concept/elons-toys/.docs/instructions.md
Labels: x:size/tiny

#1946 lasagna: fix typo in basics concept text
  concepts/basics/about.md
  concepts/basics/introduction.md
  exercises/concept/lasagna/.docs/introduction.md
Labels: x:size/small

#1947 Annalyns infiltration: test updates
  exercises/concept/annalyns-infiltration/annalyns_infiltration_test.go
Labels: x:size/small

#1948 Interest-is-Interesting: Fix float comparison
  exercises/concept/interest-is-interesting/interest_is_interesting_test.go
Labels: x:size/small

#1950 party-robot: fix typos in hints
  exercises/concept/party-robot/.docs/hints.md
Labels: x:size/tiny

#1951 Elons toys & Need for Speed
  exercises/concept/elons-toys/elons_toys_test.go
  exercises/concept/need-for-speed/need_for_speed_test.go
Labels: x:size/small, status/awaiting-contributor

#1952 party-robot: update tests
  exercises/concept/party-robot/party_robot_test.go
Labels: x:size/small, status/awaiting-contributor

#1957 Changing the variable name to number
  exercises/practice/grains/.meta/example.go
Labels: x:size/tiny

#1961 Fix typo
  exercises/practice/binary-search-tree/binary_search_tree_test.go
Labels: x:size/tiny

#1962 Explain --bench and --benchmem results by example
  docs/TESTS.md
Labels: x:size/small

#1960 Add concept exercise "vehicle-purchase" (#1934)
  config.json
  exercises/concept/vehicle-purchase/.docs/hints.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
  exercises/concept/vehicle-purchase/.meta/config.json
  exercises/concept/vehicle-purchase/.meta/design.md
  exercises/concept/vehicle-purchase/.meta/exemplar.go
  exercises/concept/vehicle-purchase/go.mod
  exercises/concept/vehicle-purchase/vehicle_purchase.go
  exercises/concept/vehicle-purchase/vehicle_purchase_test.go
Labels: x:size/medium, status/awaiting-contributor

#1966 vehicle-purchase: correct spelling of `License`. - #1965
  exercises/concept/vehicle-purchase/.docs/hints.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/.meta/exemplar.go
  exercises/concept/vehicle-purchase/vehicle_purchase.go
  exercises/concept/vehicle-purchase/vehicle_purchase_test.go
Labels: x:size/small

#1964 vehicle-purchase: fix CalculateResellPrice price description (#1934)
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/vehicle_purchase_test.go
Labels: x:size/small

#1939 error-handling: ensure `Close` is called only once
  exercises/practice/error-handling/.docs/instructions.md
  exercises/practice/error-handling/error_handling_test.go
Labels: x:size/small, status/awaiting-contributor

#1958 Add stub functions to practice exercises T-Z
  exercises/practice/tournament/tournament.go
  exercises/practice/transpose/transpose.go
  exercises/practice/twelve-days/twelve_days.go
  exercises/practice/two-bucket/two_bucket.go
  exercises/practice/variable-length-quantity/variable_length_quantity.go
  exercises/practice/word-count/word_count.go
  exercises/practice/word-count/word_count_test.go
  exercises/practice/word-search/word_search.go
  exercises/practice/word-search/word_search_test.go
  exercises/practice/wordy/wordy.go
  exercises/practice/yacht/yacht.go
  exercises/practice/zebra-puzzle/.docs/instructions.append.md
  exercises/practice/zebra-puzzle/zebra_puzzle.go
Labels: x:size/medium, status/awaiting-maintainer

#1969 Go - vehicle_purchase - fixed typo
  exercises/concept/vehicle-purchase/.meta/exemplar.go
  exercises/concept/vehicle-purchase/vehicle_purchase.go
Labels: x:size/small

#1973 Delete instructions.append.md
  exercises/practice/raindrops/.docs/instructions.append.md
Labels: x:size/small

#1975 Fix spelling
  exercises/concept/elons-toys/.docs/introduction.md
Labels: x:size/tiny
