Repository exercism/go, pull requests merged in 2021-09, with the labels that each got.

#1555 Add september-sprint label
  .appends/.github/labels.yml
Labels: x:size/tiny

#1650 Change party-robot info to only mention fmt.Sprintf (#1597)
  exercises/concept/party-robot/.docs/introduction.md
Labels: x:size/small

#1646 Fix typo in hints.md
  exercises/concept/party-robot/.docs/hints.md
Labels: x:size/tiny

#1667 [Sept Sprint] Improve Weather Forecast
  exercises/concept/weather-forecast/.docs/introduction.md
  exercises/concept/weather-forecast/weather.go
Labels: x:size/tiny

#1660 [Sept Sprint] Gross Store improvements
  concepts/maps/introduction.md
  config.json
  exercises/concept/gross-store/.docs/introduction.md
  exercises/concept/gross-store/.meta/config.json
Labels: x:size/small

#1669 Fix typo in introduction.md
  concepts/methods/introduction.md
Labels: x:size/tiny

#1666 Add `booleans` as a prereq for `card-tricks`
  config.json
Labels: x:size/tiny

#1664 Cars assemble enhance test output
  exercises/concept/cars-assemble/cars_assemble.go
  exercises/concept/cars-assemble/cars_assemble_test.go
Labels: x:size/tiny

#1663 Update the type conversion introduction
  exercises/concept/cars-assemble/.docs/introduction.md
Labels: september-sprint

#1665 Fix some of the outstanding issues with the card-tricks concept exercise
  concepts/slices/introduction.md
  exercises/concept/card-tricks/.docs/introduction.md
Labels: september-sprint

#1651 Finish off new 'packages' concept (#1586)
  concepts/functions/introduction.md
  concepts/packages/.meta/config.json
  concepts/packages/about.md
  concepts/packages/introduction.md
  concepts/packages/links.json
  concepts/variables/introduction.md
  config.json
  exercises/concept/party-robot/.docs/introduction.md
  exercises/concept/party-robot/.meta/config.json
Labels: september-sprint

#1677 weather forecast: fix failing tests
  exercises/concept/weather-forecast/.meta/exemplar.go
  exercises/concept/weather-forecast/weather_test.go
Labels: x:size/small

#1679 Fix headings in hints for annalyns-infiltration (#1678)
  exercises/concept/annalyns-infiltration/.docs/hints.md
Labels: x:size/tiny

#1657 docs: improve need for speed intro
  concepts/structs/about.md
  concepts/structs/introduction.md
  concepts/type-definitions/introduction.md
  exercises/concept/need-for-speed/.docs/introduction.md
Labels: september-sprint, status/awaiting-contributor

#1656 fix: remove struct and add TODO
  exercises/concept/need-for-speed/.docs/instructions.md
  exercises/concept/need-for-speed/need_for_speed.go
Labels: september-sprint, status/awaiting-contributor

#1688 docs: fix typo Sprinf > Sprintf
  exercises/concept/party-robot/.docs/introduction.md
Labels: x:size/tiny

#1686 Add `arithmetic-operators` as a concept for `cars-assemble`
  concepts/arithmetic-operators/.meta/config.json
  concepts/arithmetic-operators/about.md
  concepts/arithmetic-operators/introduction.md
  concepts/arithmetic-operators/links.json
  config.json
  exercises/concept/cars-assemble/.docs/introduction.md
Labels: september-sprint, status/awaiting-maintainer

#1682 Some fixes for the concept tree
  config.json
  exercises/concept/booking-up-for-beauty/.meta/design.md
  exercises/concept/cars-assemble/.meta/design.md
  exercises/concept/deep-thought/.meta/design.md
  exercises/concept/savings-account/.meta/design.md
Labels: status/awaiting-maintainer

#1680 Add welcome-to-tech-palace exercise
  concepts/strings-package/.meta/config.json
  concepts/strings-package/about.md
  concepts/strings-package/introduction.md
  concepts/strings-package/links.json
  concepts/strings/.meta/config.json
  concepts/strings/about.md
  concepts/strings/introduction.md
  concepts/strings/links.json
  config.json
  exercises/concept/welcome-to-tech-palace/.docs/hints.md
  exercises/concept/welcome-to-tech-palace/.docs/instructions.md
  exercises/concept/welcome-to-tech-palace/.docs/introduction.md
  exercises/concept/welcome-to-tech-palace/.meta/config.json
  exercises/concept/welcome-to-tech-palace/.meta/design.md
  exercises/concept/welcome-to-tech-palace/.meta/exemplar.go
  exercises/concept/welcome-to-tech-palace/go.mod
  exercises/concept/welcome-to-tech-palace/welcome_to_tech_palace.go
  exercises/concept/welcome-to-tech-palace/welcome_to_tech_palace_test.go
Labels: september-sprint, status/awaiting-contributor

#1689 Add `comparison` concept
  concepts/comparison/.meta/config.json
  concepts/comparison/about.md
  concepts/comparison/introduction.md
  concepts/comparison/links.json
  config.json
Labels: september-sprint, status/awaiting-contributor

#1690 Make party-robot depend on numbers as well as strings.
  config.json
Labels: x:size/tiny

#1696 welcome-to-tech-palace: Fix `strings.ReplaceAll()` link in hints
  exercises/concept/welcome-to-tech-palace/.docs/hints.md
Labels: x:size/tiny

#1698 doc: change the expected message to the correct function
  exercises/concept/need-for-speed/need_for_speed_test.go
Labels: x:size/tiny

#1701 Increase timeout for golangci to 5m
  .golangci.yml
Labels: status/awaiting-maintainer

#1711 Cleanup the introduction for the booleans concept
  concepts/booleans/introduction.md
Labels: status/awaiting-contributor

#1699 Fix the introduction to the conditionals-if concept.
  concepts/conditionals-if/about.md
  concepts/conditionals-if/introduction.md
  exercises/concept/cars-assemble/.docs/introduction.md
Labels: september-sprint, status/awaiting-maintainer

#1712 Fix slices concept about to be superset of introduction.
  concepts/slices/about.md
  concepts/slices/introduction.md
Labels: status/awaiting-contributor

#1705 Fill in `type-conversion` concept docs
  concepts/type-conversion/.meta/config.json
  concepts/type-conversion/about.md
  concepts/type-conversion/introduction.md
  concepts/type-conversion/links.json
Labels: september-sprint, status/awaiting-contributor

#1692 Add tasks to `the-farm` introduction
  exercises/concept/the-farm/.docs/hints.md
  exercises/concept/the-farm/.docs/instructions.md
  exercises/concept/the-farm/.meta/exemplar.go
  exercises/concept/the-farm/the_farm.go
  exercises/concept/the-farm/the_farm_test.go
Labels: september-sprint, status/awaiting-maintainer

#1706 Fill in documentation for `type-assertions`
  concepts/type-assertion/.meta/config.json
  concepts/type-assertion/about.md
  concepts/type-assertion/introduction.md
  concepts/type-assertion/links.json
Labels: september-sprint, status/awaiting-maintainer

#1725 `cars-assemble`: add a task to implement `SuccessRate` and add hints
  exercises/concept/cars-assemble/.docs/hints.md
  exercises/concept/cars-assemble/.docs/instructions.md
  exercises/concept/cars-assemble/.meta/exemplar.go
  exercises/concept/cars-assemble/cars_assemble.go
  exercises/concept/cars-assemble/cars_assemble_test.go
Labels: september-sprint, status/awaiting-maintainer

#1723 `sorting-room`: Implement exercise to teach about `type-conversion` and `type-assertion`
  config.json
  exercises/concept/sorting-room/.docs/hints.md
  exercises/concept/sorting-room/.docs/instructions.md
  exercises/concept/sorting-room/.docs/introduction.md
  exercises/concept/sorting-room/.meta/config.json
  exercises/concept/sorting-room/.meta/design.md
  exercises/concept/sorting-room/.meta/exemplar.go
  exercises/concept/sorting-room/go.mod
  exercises/concept/sorting-room/sorting_room.go
  exercises/concept/sorting-room/sorting_room_test.go
Labels: x:size/large, september-sprint, status/awaiting-maintainer
