Repository exercism/go, pull requests merged in 2022-02, with the labels that each got.

#2083 Fix 'treshold' typo in some test files
  exercises/concept/cars-assemble/cars_assemble_test.go
  exercises/concept/interest-is-interesting/interest_is_interesting_test.go
  exercises/concept/vehicle-purchase/vehicle_purchase_test.go
Labels: x:size/tiny

#2086 fix: rephrasing introduction.md and about.md since golang.org was replaced by go.dev
  concepts/basics/about.md
  concepts/basics/introduction.md
Labels: x:size/tiny

#2081 runes: hex and decimal examples
  concepts/runes/about.md
Labels: x:size/small, status/awaiting-contributor

#2096 test(election-date): correct typo in test name
  exercises/concept/election-day/election_day_test.go
Labels: x:size/tiny

#2097 need-for-speed: Add test cases for car with positive initial distance
  exercises/concept/need-for-speed/need_for_speed_test.go
Labels: x:size/small

#2094 Fix extra tests for arch 386 running in an older version of Go
  .github/workflows/exercise-tests.yml
Labels: x:size/small

#2091 add variadic function concept exercise
  concepts/variadic-functions/.meta/config.json
  concepts/variadic-functions/about.md
  concepts/variadic-functions/introduction.md
  concepts/variadic-functions/links.json
  config.json
Labels: x:size/medium, status/awaiting-contributor

#2101 hamming: Update link leading to leap exercise
  exercises/practice/hamming/.docs/instructions.append.md
Labels: x:size/tiny

#2102 interest-is-interesting: added for-loop prerequisite
  config.json
Labels: x:size/tiny

#2104 robot-simulator: Fix formatting on append instructions
  exercises/practice/robot-simulator/.docs/instructions.append.md
Labels: x:size/small

#2112 Sorting room instructions and testcase
  exercises/concept/sorting-room/.docs/instructions.md
Labels: x:size/tiny
