Repository exercism/go, pull requests merged in 2022-06, with the labels that each got.

#2229 Improve Linked List
  exercises/practice/linked-list/.docs/instructions.append.md
  exercises/practice/linked-list/.meta/example.go
  exercises/practice/linked-list/cases_test.go
  exercises/practice/linked-list/linked_list.go
Labels: x:size/medium

#2231 Fix #2230
  exercises/practice/pig-latin/pig_latin_test.go
Labels: x:size/small

#2234 Add eldorandev to contributers of linked-list task
  exercises/practice/linked-list/.meta/config.json
Labels: x:size/tiny

#2238 Switch windSpeed and windDirection
  exercises/concept/meteorology/.docs/hints.md
  exercises/concept/meteorology/.docs/instructions.md
Labels: x:size/tiny

#2236 logs-logs-logs: add more tests to better cover multiple characters case
  exercises/concept/logs-logs-logs/.docs/instructions.md
  exercises/concept/logs-logs-logs/logs_logs_logs_test.go
Labels: x:size/small

#2244 fix function arguments and parameters missmatch
  concepts/functions/about.md
  concepts/functions/introduction.md
  exercises/concept/lasagna-master/.docs/introduction.md
Labels: x:size/tiny

#2246 time: add link from go-by-example: time formatting / parsing
  concepts/time/links.json
Labels: x:size/tiny

#2248 Minor mistake in exercise 3. example
  exercises/concept/meteorology/.docs/instructions.md
Labels: x:size/tiny

#2245 Add linking issues to PRs instructions to pr-commenter
  .github/pr-commenter.yml
Labels: x:size/small

#2247 isbn_verifier task: run each test dataset in a separate TC
  exercises/practice/isbn-verifier/isbn_verifier_test.go
Labels: x:size/small

#2249 elons-toys: improve description for first stage
  exercises/concept/elons-toys/.docs/instructions.md
Labels: x:size/small

#2251 regenerated test-cases
  exercises/practice/luhn/.meta/config.json
  exercises/practice/luhn/.meta/tests.toml
  exercises/practice/luhn/cases_test.go
Labels: x:size/small

#2235 Need for Speed: Minor improvements (#1755)
  concepts/structs/.meta/config.json
  concepts/structs/about.md
  concepts/structs/introduction.md
  exercises/concept/need-for-speed/.docs/instructions.md
  exercises/concept/need-for-speed/.docs/introduction.md
  exercises/concept/need-for-speed/.meta/config.json
Labels: x:size/medium, status/awaiting-maintainer

#2197 Changed "Output" to "=>" - Cars Assemble (Fixes #2196)
  exercises/concept/cars-assemble/.docs/instructions.md
Labels: x:size/small, status/awaiting-contributor

#2253 Update of the "generating test cases" section of the readme
  README.md
Labels: x:size/small, status/awaiting-contributor

#2261 Updated anchors in readme.md
  README.md
Labels: x:size/tiny

#2264 concepts/type-assertion: fix change fmt.Println to fmt.Printf and improve type switch example
  concepts/type-assertion/about.md
  concepts/type-assertion/introduction.md
  exercises/concept/sorting-room/.docs/introduction.md
Labels: x:size/small

#2255 Added the test-cases from canonical-data.json to exercise diamond
  exercises/practice/diamond/.meta/gen.go
  exercises/practice/diamond/.meta/tests.toml
  exercises/practice/diamond/cases_test.go
  exercises/practice/diamond/diamond_test.go
Labels: x:size/medium, status/awaiting-contributor

#2266 Fixed #2202 edited and added "=>" instead of "Output:
  exercises/concept/booking-up-for-beauty/.docs/instructions.md
  exercises/concept/card-tricks/.docs/introduction.md
  exercises/concept/election-day/.docs/instructions.md
  exercises/concept/elons-toys/.docs/instructions.md
  exercises/concept/interest-is-interesting/.docs/instructions.md
  exercises/concept/party-robot/.docs/instructions.md
  exercises/concept/savings-account/.docs/instructions.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/welcome-to-tech-palace/.docs/instructions.md
Labels: x:size/small

#2260 bank-account: added instructions for function implementation
  exercises/practice/bank-account/.docs/instructions.append.md
Labels: x:size/small, status/awaiting-contributor

#2267 Fix typo in comment
  exercises/concept/need-for-speed/need_for_speed.go
Labels: x:size/tiny

#2268 parallel-letter-frequency: remove redandunt link, add more
  exercises/practice/parallel-letter-frequency/.docs/instructions.append.md
Labels: x:size/small

#2269 Fixed "Output" (#2202) - Some Remaining files
  concepts/booleans/about.md
  concepts/booleans/introduction.md
  concepts/strings-package/about.md
  concepts/strings-package/introduction.md
Labels: x:size/small

#2270 Fixed "Output" format (#2202) - constants and conditionals-if
  concepts/constants/about.md
Labels: x:size/small

#2272 bank-account: fix links formatting
  exercises/practice/bank-account/.docs/instructions.append.md
Labels: x:size/small

#2200 Fixed "Output" - Welcome To The Tech Palace (Fixes #2156)
  concepts/strings/about.md
  concepts/strings/introduction.md
  exercises/concept/welcome-to-tech-palace/.docs/instructions.md
  exercises/concept/welcome-to-tech-palace/.docs/introduction.md
Labels: x:size/small, status/awaiting-contributor

#2273 fix typo `will b`
  concepts/structs/about.md
  concepts/structs/introduction.md
Labels: x:size/tiny

#2274 Fix headers in bank account instructions append
  exercises/practice/bank-account/.docs/instructions.append.md
Labels: x:rep/small
