Repository exercism/go, pull requests merged in 2022-04, with the labels that each got.

#2143 Added test case to ensure fives is implemented
  exercises/practice/yacht/.meta/tests.toml
  exercises/practice/yacht/cases_test.go
Labels: x:size/small

#2103 New concept First-Class Functions
  concepts/first-class-functions/.meta/config.json
  concepts/first-class-functions/about.md
  concepts/first-class-functions/introduction.md
  concepts/first-class-functions/links.json
  config.json
  exercises/concept/expenses/.docs/hints.md
  exercises/concept/expenses/.docs/instructions.md
  exercises/concept/expenses/.docs/introduction.md
  exercises/concept/expenses/.meta/config.json
  exercises/concept/expenses/.meta/design.md
  exercises/concept/expenses/.meta/exemplar.go
  exercises/concept/expenses/expenses.go
  exercises/concept/expenses/expenses_test.go
  exercises/concept/expenses/go.mod
Labels: x:size/large, status/awaiting-contributor

#2150 Docs(`expenses`): correct `Total` function name in `instructions.md`
  exercises/concept/expenses/.docs/instructions.md
Labels: x:size/small

#2151 Tree-building exercise: added custom nodeEqual method, added type def
  exercises/practice/tree-building/tree_building.go
  exercises/practice/tree-building/tree_building_test.go
Labels: x:size/small

#2152 Fix typo on "groceries" in expenses exercise
  exercises/concept/expenses/.docs/instructions.md
  exercises/concept/expenses/expenses_test.go
Labels: x:size/small

#2153 POV tests - changed to more usual pattern
  exercises/practice/pov/.meta/config.json
  exercises/practice/pov/cases_test.go
  exercises/practice/pov/pov_test.go
Labels: x:size/small

#2154 Vehicle purchase exercise - removed UTF-16 ref, renamed ordering
  exercises/concept/vehicle-purchase/.docs/hints.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
  exercises/concept/vehicle-purchase/.meta/exemplar.go
  exercises/concept/vehicle-purchase/vehicle_purchase.go
Labels: x:size/small

#2158 Fix typo in expenses exercise and first-class-function concept
  concepts/first-class-functions/about.md
  concepts/first-class-functions/introduction.md
  exercises/concept/expenses/.docs/instructions.md
  exercises/concept/expenses/.docs/introduction.md
Labels: x:size/small

#2161 Removed excess percentage signs
  exercises/concept/cars-assemble/cars_assemble_test.go
Labels: x:size/small, status/awaiting-contributor

#2160 Update introduction.md
  concepts/first-class-functions/about.md
  concepts/first-class-functions/introduction.md
  exercises/concept/expenses/.docs/introduction.md
Labels: x:size/small, status/awaiting-contributor

#2159 Regular expression concept with exercise
  concepts/regular-expressions/.meta/config.json
  concepts/regular-expressions/about.md
  concepts/regular-expressions/introduction.md
  concepts/regular-expressions/links.json
  config.json
  exercises/concept/parsing-log-files/.docs/hints.md
  exercises/concept/parsing-log-files/.docs/instructions.md
  exercises/concept/parsing-log-files/.docs/introduction.md
  exercises/concept/parsing-log-files/.meta/config.json
  exercises/concept/parsing-log-files/.meta/design.md
  exercises/concept/parsing-log-files/.meta/exemplar.go
  exercises/concept/parsing-log-files/go.mod
  exercises/concept/parsing-log-files/parsing_log_files.go
  exercises/concept/parsing-log-files/parsing_log_files_test.go
Labels: x:size/large, status/awaiting-contributor

#2157 Typo: e.g.
  concepts/arithmetic-operators/about.md
  concepts/arithmetic-operators/introduction.md
  exercises/concept/cars-assemble/.docs/introduction.md
  exercises/concept/election-day/.docs/hints.md
  exercises/concept/party-robot/.docs/instructions.md
  exercises/concept/sorting-room/.docs/hints.md
Labels: x:size/small

#2167 Methods concept: make it clear that there are two types of receivers
  concepts/methods/about.md
  concepts/methods/introduction.md
  exercises/concept/elons-toys/.docs/introduction.md
Labels: x:size/small

#2168 Methods concept: two minor fixes about grammar and punctuation
  concepts/methods/about.md
  concepts/methods/introduction.md
  exercises/concept/elons-toys/.docs/introduction.md
Labels: x:size/tiny, status/awaiting-contributor

#2175 Tree Building: Exercise should be labeled as medium not easy #2172
  config.json
Labels: x:size/tiny

#2176 election-day: fix typo in NewVoteCounter comment
  exercises/concept/election-day/.meta/exemplar.go
  exercises/concept/election-day/election_day.go
Labels: x:size/tiny

#2177 the-farm: add missing syntax highlighting in instructions
  exercises/concept/the-farm/.docs/instructions.md
Labels: x:size/tiny

#2180 docs(expenses): clarify instructions
  exercises/concept/expenses/.docs/instructions.md
Labels: x:size/small

#2186 Add instructions to create errors
  config.json
  exercises/concept/expenses/.meta/design.md
Labels: x:size/small

#2171 add more details and examples to the introduction
  concepts/strings/.meta/config.json
  concepts/strings/about.md
  concepts/strings/introduction.md
  exercises/concept/welcome-to-tech-palace/.docs/introduction.md
  exercises/concept/welcome-to-tech-palace/.meta/config.json
Labels: x:size/small

#2189 Animal Magic: Set Icon
  exercises/concept/animal-magic/.meta/config.json
Labels: x:size/small

#2192 Clarify blackjack instructions
  exercises/concept/blackjack/.docs/instructions.md
Labels: x:size/tiny

#2195 Changed "Output" to "=>" in: Gopher's Gorgeous Lasagna (Fixes #2194)
  exercises/concept/lasagna/.docs/instructions.md
Labels: x:size/small

#2198 Fix error in TestRemainingOvenTime, fix typos
  exercises/concept/lasagna/lasagna_test.go
Labels: x:size/small

#2193 Issue #2181: Improve functions introduction
  concepts/functions/about.md
  concepts/functions/introduction.md
  exercises/concept/lasagna-master/.docs/instructions.md
  exercises/concept/lasagna-master/.docs/introduction.md
Labels: x:size/small, status/awaiting-contributor

#2203 Issue #2090: linked list add note for Node struct field Value
  exercises/practice/linked-list/.meta/example.go
  exercises/practice/linked-list/linked_list.go
  exercises/practice/linked-list/linked_list_test.go
Labels: x:rep/small

#2207 #2155: Clarify when an exercise is tested with the `-race` flag
  docs/TESTS.md
  exercises/practice/bank-account/.docs/instructions.append.md
Labels: status/awaiting-contributor, x:rep/small
