Repository exercism/go, pull requests merged in 2022-03, with the labels that each got.

#2114 Clarify error message for bird-count
  exercises/concept/bird-watcher/bird_watcher_test.go
Labels: x:size/small

#2118 minesweeper-api-change
  exercises/practice/minesweeper/.meta/config.json
  exercises/practice/minesweeper/.meta/example.go
  exercises/practice/minesweeper/board.go
  exercises/practice/minesweeper/minesweeper.go
  exercises/practice/minesweeper/minesweeper_test.go
Labels: x:size/medium

#2119 Clarify instructions
  exercises/concept/the-farm/.docs/instructions.md
Labels: x:size/small

#2127 Fix typos in test names
  exercises/concept/election-day/election_day_test.go
Labels: x:size/tiny

#2128 elons_toys_test - Use consistent formatting
  exercises/concept/elons-toys/elons_toys_test.go
Labels: x:size/tiny

#2121 Pov tree logic ops
  exercises/practice/pov/.docs/instructions.append.md
  exercises/practice/pov/.meta/config.json
  exercises/practice/pov/.meta/example.go
  exercises/practice/pov/pov.go
  exercises/practice/pov/pov_test.go
  exercises/practice/pov/test_cases.go
Labels: x:size/medium, status/awaiting-maintainer

#2136 Overhaul of BlackJack concept exercise
  exercises/concept/blackjack/.docs/hints.md
  exercises/concept/blackjack/.docs/instructions.md
  exercises/concept/blackjack/.meta/config.json
  exercises/concept/blackjack/.meta/exemplar.go
  exercises/concept/blackjack/blackjack.go
  exercises/concept/blackjack/blackjack_test.go
Labels: x:size/medium

#2130 Card Tricks: Adapt to current concept tree progression #1990
  config.json
  exercises/concept/card-tricks/.docs/hints.md
  exercises/concept/card-tricks/.docs/instructions.md
  exercises/concept/card-tricks/.docs/introduction.md
  exercises/concept/card-tricks/.meta/config.json
  exercises/concept/card-tricks/.meta/design.md
  exercises/concept/card-tricks/.meta/exemplar.go
  exercises/concept/card-tricks/card_tricks.go
  exercises/concept/card-tricks/card_tricks_test.go
Labels: x:size/medium, status/awaiting-maintainer

#2138 Add missing test case for Blackjack (#2136)
  exercises/concept/blackjack/blackjack_test.go
Labels: x:size/small, status/awaiting-contributor

#2140 Updated robot_name_test.go to fix a one word typo.
  exercises/practice/robot-name/robot_name_test.go
Labels: x:size/tiny

#2123 Binary-search-tree #2113
  exercises/practice/binary-search-tree/.meta/config.json
  exercises/practice/binary-search-tree/.meta/example.go
  exercises/practice/binary-search-tree/binary_search_tree.go
  exercises/practice/binary-search-tree/binary_search_tree_test.go
Labels: x:size/medium, status/awaiting-contributor

#2139 Implement new concept with exercise: randomness
  concepts/randomness/.meta/config.json
  concepts/randomness/about.md
  concepts/randomness/introduction.md
  concepts/randomness/links.json
  config.json
  exercises/concept/animal-magic/.docs/hints.md
  exercises/concept/animal-magic/.docs/instructions.md
  exercises/concept/animal-magic/.docs/introduction.md
  exercises/concept/animal-magic/.meta/config.json
  exercises/concept/animal-magic/.meta/design.md
  exercises/concept/animal-magic/.meta/exemplar.go
  exercises/concept/animal-magic/animal_magic.go
  exercises/concept/animal-magic/animal_magic_test.go
  exercises/concept/animal-magic/go.mod
Labels: x:size/large, status/awaiting-contributor

#2144 Fix links in randomness exercise
  concepts/randomness/about.md
  concepts/randomness/introduction.md
Labels: x:size/small

#2145 Fixing a couple of links in concepts/randomness
  concepts/randomness/about.md
  concepts/randomness/introduction.md
  concepts/randomness/links.json
  config.json
  exercises/concept/animal-magic/.docs/introduction.md
Labels: x:size/small
