Repository exercism/go, pull requests merged in 2022-08, with the labels that each got.

#2409 Added part about additional test cases to README
  README.md
Labels: x:rep/small

#2403 Added run-generators to README
  README.md
Labels: x:rep/small

#2341 markdown: updated exercise generator to new test generator
  exercises/practice/markdown/.meta/config.json
  exercises/practice/markdown/.meta/example.go
  exercises/practice/markdown/.meta/gen.go
  exercises/practice/markdown/.meta/tests.toml
Labels: x:rep/medium

#2404 Wrong formatted example
  exercises/concept/welcome-to-tech-palace/.docs/instructions.md
Labels: x:rep/small

#2413 Modify Chessboard exercise to comply with standard chess notation
  exercises/concept/chessboard/.docs/hints.md
  exercises/concept/chessboard/.docs/instructions.md
  exercises/concept/chessboard/.meta/exemplar.go
  exercises/concept/chessboard/chessboard.go
  exercises/concept/chessboard/chessboard_test.go
Labels: x:rep/medium

#2419 updated all exercises with generators
  exercises/practice/word-count/.docs/instructions.md
Labels: x:rep/tiny

#2415 Need For Speed | Added Formula for Calculating Race Distance and Battery Drain Rate
  exercises/concept/need-for-speed/.docs/hints.md
Labels: x:rep/small

#2420 Animal Magic: Added test case for GenerateWandEnergy()
  exercises/concept/animal-magic/animal_magic_test.go
Labels: x:rep/small

#2427 Robot Simulator: Drop "Define Dir" as it is defined already; update who sends the report.
  exercises/practice/robot-simulator/.docs/instructions.append.md
  exercises/practice/robot-simulator/robot_simulator.go
Labels: x:rep/small

#2430 added usage of subtests for exercise bowling
  exercises/concept/animal-magic/animal_magic_test.go
  exercises/practice/bowling/bowling_test.go
Labels: x:rep/small

#2431 added usage of subtests for exercise crypto-square
  exercises/practice/crypto-square/.meta/config.json
  exercises/practice/crypto-square/crypto_square_test.go
Labels: x:rep/small

#2444 Fix flaky animal magic test on windows
  exercises/concept/animal-magic/animal_magic_test.go
Labels: x:rep/small

#2451 fixed failure of tests
  exercises/practice/armstrong-numbers/armstrong_numbers_test.go
  exercises/practice/gigasecond/gigasecond_test.go
Labels: x:rep/small

#2453 Remove semicolon from a Go code example
  exercises/concept/parsing-log-files/.docs/instructions.md
Labels: x:rep/tiny

#2437 fixed bonus tests
  exercises/practice/two-bucket/bonus_test.go
  exercises/practice/two-bucket/two_bucket_test.go
Labels: x:rep/small

#2435 added usage of subtests food-chain
  exercises/practice/food-chain/.meta/config.json
  exercises/practice/food-chain/food_chain_test.go
Labels: status/awaiting-contributor, x:rep/small

#2439 added usage of subtests to the kindergarten-garden exercise
  exercises/practice/kindergarten-garden/.meta/config.json
  exercises/practice/kindergarten-garden/kindergarten_garden_test.go
Labels: status/awaiting-contributor, x:rep/small

#2438 added usage of subtests to the house exercise
  exercises/practice/house/.meta/config.json
  exercises/practice/house/house_test.go
Labels: status/awaiting-contributor, x:rep/small

#2434 added usage of subtest for etl
  exercises/practice/etl/.meta/config.json
  exercises/practice/etl/etl_test.go
Labels: status/awaiting-contributor, x:rep/small

#2432 added usage of subtests to difference-of-squares
  exercises/practice/difference-of-squares/.meta/config.json
  exercises/practice/difference-of-squares/.meta/example.go
  exercises/practice/difference-of-squares/difference_of_squares_test.go
Labels: status/awaiting-contributor, x:rep/small

#2428 added subtests to chessboard
  exercises/concept/chessboard/.meta/config.json
  exercises/concept/chessboard/chessboard_test.go
Labels: status/awaiting-contributor, x:rep/small

#2447 added usage of subtests for exercise matrix
  exercises/practice/matrix/.meta/config.json
  exercises/practice/matrix/matrix_test.go
Labels: x:rep/small
