Repository exercism/go, pull requests merged in 2022-07, with the labels that each got.

#2277 changed t.Skip to t.Fatalf if input of test is invalid
  exercises/practice/kindergarten-garden/kindergarten_garden_test.go
  exercises/practice/matrix/matrix_test.go
Labels: x:rep/small

#2283 added new test-cases to exercise chessboard
  exercises/concept/chessboard/chessboard_test.go
Labels: x:size/small

#2285 Add extra test cases for IncrementVoteCount in election_day
  exercises/concept/election-day/election_day_test.go
Labels: x:rep/small

#2286 Tweak weather forecast story for flow
  exercises/concept/weather-forecast/.docs/instructions.md
Labels: x:rep/small

#2287 Add punctuation to function comments in concept instructions
  concepts/basics/introduction.md
Labels: x:rep/tiny

#2284 Added new practice exercise: state-of-tic-tac-toe
  config.json
  exercises/practice/state-of-tic-tac-toe/.docs/instructions.md
  exercises/practice/state-of-tic-tac-toe/.meta/config.json
  exercises/practice/state-of-tic-tac-toe/.meta/example.go
  exercises/practice/state-of-tic-tac-toe/.meta/gen.go
  exercises/practice/state-of-tic-tac-toe/.meta/tests.toml
  exercises/practice/state-of-tic-tac-toe/cases_test.go
  exercises/practice/state-of-tic-tac-toe/go.mod
  exercises/practice/state-of-tic-tac-toe/state_of_tic_tac_toe.go
  exercises/practice/state-of-tic-tac-toe/state_of_tic_tac_toe_test.go
Labels: status/awaiting-contributor, x:rep/large

#2291 Added additional information and better formatting to explain why TestAssignTable…
  exercises/concept/party-robot/party_robot_test.go
Labels: x:rep/small

#2295 meteorology: improved formatting of instructions
  exercises/concept/meteorology/.docs/instructions.md
  exercises/concept/meteorology/.meta/config.json
Labels: x:rep/tiny

#2294 Additional test cases for logs-logs-logs
  exercises/concept/logs-logs-logs/logs_logs_logs_test.go
Labels: status/awaiting-contributor, x:rep/small

#2297 parsing-log-files: added test case
  exercises/concept/parsing-log-files/.meta/config.json
  exercises/concept/parsing-log-files/parsing_log_files_test.go
Labels: status/awaiting-contributor, x:rep/small

#2299 Quote class names
  exercises/practice/error-handling/.docs/instructions.md
Labels: status/awaiting-contributor, x:rep/small

#2279 Update of testcase generator to latest JSON format
  exercises/practice/bowling/.meta/config.json
  exercises/practice/bowling/.meta/gen.go
  exercises/practice/bowling/cases_test.go
  exercises/practice/diamond/.meta/config.json
  exercises/practice/diamond/.meta/gen.go
  exercises/practice/diamond/cases_test.go
  exercises/practice/forth/.meta/config.json
  exercises/practice/forth/.meta/gen.go
  exercises/practice/forth/.meta/tests.toml
  exercises/practice/forth/cases_test.go
  exercises/practice/forth/forth_test.go
  exercises/practice/minesweeper/minesweeper.go
  exercises/practice/saddle-points/.meta/config.json
  exercises/practice/saddle-points/.meta/example.go
  exercises/practice/saddle-points/.meta/gen.go
  exercises/practice/saddle-points/.meta/tests.toml
  exercises/practice/saddle-points/cases_test.go
  exercises/practice/saddle-points/saddle_points_test.go
  exercises/practice/scrabble-score/scrabble_score.go
  gen/filter.go
  gen/filter_test.go
  gen/gen.go
  gen/local.go
  gen/property.go
  gen/remote.go
  gen/toml.go
Labels: x:rep/large

#2305 [Functions Concept]: Added word statements to the return section for clarity
  concepts/functions/about.md
  concepts/functions/introduction.md
  exercises/concept/lasagna-master/.docs/introduction.md
Labels: x:rep/tiny

#2304 added instructions how to add a new exercise generator
  README.md
Labels: x:rep/small

#2306 diamond: removed expected \n from last line
  exercises/practice/diamond/.meta/example.go
  exercises/practice/diamond/diamond_test.go
Labels: x:rep/small

#2307 acronym: updated exercise generator to new test generator and updated exercise…
  exercises/practice/acronym/.docs/instructions.md
  exercises/practice/acronym/.meta/config.json
  exercises/practice/acronym/.meta/gen.go
  exercises/practice/acronym/acronym_test.go
  exercises/practice/acronym/cases_test.go
Labels: status/awaiting-contributor, x:rep/small

#2308 all-your-base: updated exercise generator to new test generator and u…
  exercises/practice/all-your-base/.meta/config.json
  exercises/practice/all-your-base/.meta/gen.go
  exercises/practice/all-your-base/all_your_base_test.go
  exercises/practice/all-your-base/cases_test.go
Labels: status/awaiting-contributor, x:rep/small

#2309 allergies: updated exercise generator to new test generator
  exercises/practice/allergies/.meta/config.json
  exercises/practice/allergies/.meta/gen.go
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/allergies_test.go
  exercises/practice/allergies/cases_test.go
Labels: status/awaiting-contributor, x:rep/small

#2313 atbash-cipher: updated exercise generator to new test generator
  exercises/practice/atbash-cipher/.meta/config.json
  exercises/practice/atbash-cipher/.meta/gen.go
  exercises/practice/atbash-cipher/.meta/tests.toml
  exercises/practice/atbash-cipher/atbash_cipher_test.go
  exercises/practice/atbash-cipher/cases_test.go
Labels: x:rep/small

#2315 binary-search: updated exercise generator to new test generator
  exercises/practice/binary-search/.meta/config.json
  exercises/practice/binary-search/.meta/gen.go
  exercises/practice/binary-search/binary_search_test.go
  exercises/practice/binary-search/cases_test.go
Labels: x:rep/small

#2316 bob: updated exercise generator to new test generator
  exercises/practice/bob/.meta/config.json
  exercises/practice/bob/.meta/gen.go
  exercises/practice/bob/bob_test.go
  exercises/practice/bob/cases_test.go
Labels: x:rep/small

#2317 book-store: updated exercise generator to new test generator
  exercises/practice/book-store/.docs/instructions.md
  exercises/practice/book-store/.meta/config.json
  exercises/practice/book-store/.meta/gen.go
  exercises/practice/book-store/.meta/tests.toml
  exercises/practice/book-store/book_store_test.go
  exercises/practice/book-store/cases_test.go
Labels: x:rep/small

#2319 clock: updated exercise generator to new test generator
  exercises/practice/clock/.meta/config.json
  exercises/practice/clock/.meta/gen.go
  exercises/practice/clock/cases_test.go
  exercises/practice/clock/clock_test.go
Labels: x:rep/small

#2321 connect: updated exercise generator to new test generator
  exercises/practice/connect/.meta/config.json
  exercises/practice/connect/.meta/gen.go
  exercises/practice/connect/cases_test.go
  exercises/practice/connect/connect_test.go
Labels: x:rep/small

#2322 custom-set: updated exercise generator to new test generator
  exercises/practice/custom-set/.meta/config.json
  exercises/practice/custom-set/.meta/gen.go
  exercises/practice/custom-set/cases_test.go
  exercises/practice/custom-set/custom_set_test.go
  gen/gen.go
Labels: x:rep/small

#2325 darts: updated exercise generator to new test generator
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/darts/.meta/config.json
  exercises/practice/darts/.meta/gen.go
  exercises/practice/darts/cases_test.go
  exercises/practice/darts/darts_test.go
Labels: x:rep/small

#2338 largest-series-product: updated exercise generator to new test generator
  exercises/practice/largest-series-product/.docs/instructions.md
  exercises/practice/largest-series-product/.meta/config.json
  exercises/practice/largest-series-product/.meta/gen.go
  exercises/practice/largest-series-product/.meta/tests.toml
  exercises/practice/largest-series-product/cases_test.go
  exercises/practice/largest-series-product/largest_series_product_test.go
Labels: x:rep/small

#2326 dominoes: updated exercise generator to new test generator
  exercises/practice/dominoes/.meta/config.json
  exercises/practice/dominoes/.meta/gen.go
  exercises/practice/dominoes/cases_test.go
  exercises/practice/dominoes/dominoes_test.go
  gen/gen.go
Labels: x:rep/small

#2318 change: updated exercise generator to new test generator
  exercises/practice/change/.meta/config.json
  exercises/practice/change/.meta/gen.go
  exercises/practice/change/.meta/tests.toml
  exercises/practice/change/cases_test.go
  exercises/practice/change/change_test.go
Labels: x:rep/small

#2327 flatten-array: updated exercise generator to new test generator
  exercises/practice/flatten-array/.meta/config.json
  exercises/practice/flatten-array/.meta/gen.go
  exercises/practice/flatten-array/.meta/tests.toml
  exercises/practice/flatten-array/cases_test.go
  exercises/practice/flatten-array/flatten_array_test.go
Labels: x:rep/small

#2328 gigasecond: updated exercise generator to new test generator
  exercises/practice/gigasecond/.meta/config.json
  exercises/practice/gigasecond/.meta/gen.go
  exercises/practice/gigasecond/cases_test.go
  exercises/practice/gigasecond/gigasecond_test.go
Labels: x:rep/small

#2311 anagram: updated exercise generator to new test generator
  exercises/practice/anagram/.docs/instructions.md
  exercises/practice/anagram/.meta/config.json
  exercises/practice/anagram/.meta/gen.go
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/anagram_test.go
  exercises/practice/anagram/cases_test.go
Labels: status/awaiting-contributor, x:rep/small

#2332 isbn-verifier: updated exercise generator to new test generator
  exercises/practice/isbn-verifier/.docs/instructions.md
  exercises/practice/isbn-verifier/.meta/config.json
  exercises/practice/isbn-verifier/.meta/gen.go
  exercises/practice/isbn-verifier/.meta/tests.toml
  exercises/practice/isbn-verifier/cases_test.go
  exercises/practice/isbn-verifier/isbn_verifier_test.go
Labels: x:rep/small

#2333 Made a few concept code example to follow the standard format
  exercises/concept/census/.docs/instructions.md
  exercises/concept/meteorology/.docs/instructions.md
Labels: x:rep/small

#2337 isogram: updated exercise generator to new test generator
  exercises/practice/isogram/.meta/config.json
  exercises/practice/isogram/.meta/gen.go
  exercises/practice/isogram/.meta/tests.toml
  exercises/practice/isogram/cases_test.go
  exercises/practice/isogram/isogram_test.go
Labels: x:rep/small

#2339 leap: updated exercise generator to new test generator
  exercises/practice/leap/.meta/config.json
  exercises/practice/leap/.meta/gen.go
  exercises/practice/leap/cases_test.go
  exercises/practice/leap/leap_test.go
Labels: x:rep/small

#2340 luhn: updated exercise generator to new test generator
  exercises/practice/luhn/.meta/gen.go
  exercises/practice/luhn/cases_test.go
  exercises/practice/luhn/luhn_test.go
Labels: x:rep/small

#2342 matching-brackets: updated exercise generator to new test generator
  exercises/practice/matching-brackets/.meta/config.json
  exercises/practice/matching-brackets/.meta/gen.go
  exercises/practice/matching-brackets/.meta/tests.toml
  exercises/practice/matching-brackets/cases_test.go
  exercises/practice/matching-brackets/matching_brackets_test.go
Labels: x:rep/small

#2343 meetup: updated exercise generator to new test generator
  exercises/practice/meetup/.docs/instructions.md
  exercises/practice/meetup/.meta/config.json
  exercises/practice/meetup/.meta/gen.go
  exercises/practice/meetup/cases_test.go
  exercises/practice/meetup/meetup.go
  exercises/practice/meetup/meetup_test.go
Labels: x:rep/small

#2344 nth-prime: updated exercise generator to new test generator
  exercises/practice/nth-prime/.meta/config.json
  exercises/practice/nth-prime/.meta/gen.go
  exercises/practice/nth-prime/cases_test.go
  exercises/practice/nth-prime/nth_prime_test.go
Labels: x:rep/small

#2345 nucldeotide-count: updated exercise generator to new test generator
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/nucleotide-count/.meta/gen.go
  exercises/practice/nucleotide-count/cases_test.go
  exercises/practice/nucleotide-count/nucleotide_count_test.go
Labels: x:rep/small

#2346 pangram: updated exercise generator to new test generator
  exercises/practice/pangram/.docs/instructions.md
  exercises/practice/pangram/.meta/config.json
  exercises/practice/pangram/.meta/gen.go
  exercises/practice/pangram/.meta/tests.toml
  exercises/practice/pangram/cases_test.go
  exercises/practice/pangram/pangram_test.go
Labels: x:rep/small

#2347 perfect-numbers: updated exercise generator to new test generator
  exercises/practice/perfect-numbers/.meta/config.json
  exercises/practice/perfect-numbers/.meta/example.go
  exercises/practice/perfect-numbers/.meta/gen.go
  exercises/practice/perfect-numbers/cases_test.go
  exercises/practice/perfect-numbers/perfect_numbers_test.go
Labels: x:rep/small

#2348 phone-number: updated exercise generator to new test generator
  exercises/practice/phone-number/.meta/config.json
  exercises/practice/phone-number/.meta/gen.go
  exercises/practice/phone-number/.meta/tests.toml
  exercises/practice/phone-number/cases_test.go
  exercises/practice/phone-number/phone_number_test.go
Labels: x:rep/small

#2349 pig-latin: updated exercise generator to new test generator
  exercises/practice/pig-latin/.meta/config.json
  exercises/practice/pig-latin/.meta/gen.go
  exercises/practice/pig-latin/cases_test.go
  exercises/practice/pig-latin/pig_latin_test.go
Labels: x:rep/small

#2350 poker: updated exercise generator to new test generator
  exercises/practice/poker/.meta/config.json
  exercises/practice/poker/.meta/gen.go
  exercises/practice/poker/.meta/tests.toml
  exercises/practice/poker/cases_test.go
  exercises/practice/poker/poker_test.go
Labels: x:rep/small

#2353 prime-factors: updated exercise generator to new test generator
  exercises/practice/prime-factors/.meta/config.json
  exercises/practice/prime-factors/.meta/gen.go
  exercises/practice/prime-factors/.meta/tests.toml
  exercises/practice/prime-factors/cases_test.go
  exercises/practice/prime-factors/prime_factors_test.go
Labels: x:rep/small

#2354 proverb: updated exercise generator to new test generator
  exercises/practice/proverb/.meta/config.json
  exercises/practice/proverb/.meta/gen.go
  exercises/practice/proverb/cases_test.go
  exercises/practice/proverb/proverb_test.go
Labels: x:rep/small

#2355 rail-fence-cipher: updated exercise generator to new test generator
  exercises/practice/rail-fence-cipher/.meta/config.json
  exercises/practice/rail-fence-cipher/.meta/gen.go
  exercises/practice/rail-fence-cipher/cases_test.go
  exercises/practice/rail-fence-cipher/rail_fence_cipher_test.go
Labels: x:rep/small

#2331 hamming: updated exercise generator to new test generator
  exercises/practice/hamming/.meta/config.json
  exercises/practice/hamming/.meta/gen.go
  exercises/practice/hamming/.meta/tests.toml
  exercises/practice/hamming/cases_test.go
  exercises/practice/hamming/hamming_test.go
Labels: status/awaiting-contributor, x:rep/small

#2356 Fixed Kindergarten garden go mod file (#2351)
  exercises/practice/kindergarten-garden/go.mod
Labels: x:rep/small

#2336 lasagna: Fix ElapsedTime doc comment
  exercises/concept/lasagna/lasagna.go
Labels: status/awaiting-contributor, x:rep/tiny

#2365 Added nil test case to census exercise
  exercises/concept/census/.meta/exemplar.go
  exercises/concept/census/census_test.go
Labels: x:rep/small

#2375 card-tricks: use "values" instead of "value" in `PrependItems` function
  exercises/concept/card-tricks/.meta/exemplar.go
  exercises/concept/card-tricks/card_tricks.go
Labels: x:rep/small

#2357 raindrops: updated exercise generator to new test generator
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/raindrops/.meta/gen.go
  exercises/practice/raindrops/cases_test.go
  exercises/practice/raindrops/raindrops_test.go
Labels: x:rep/small

#2359 reverse-string: updated exercise generator to new test generator
  exercises/practice/reverse-string/.meta/config.json
  exercises/practice/reverse-string/.meta/gen.go
  exercises/practice/reverse-string/cases_test.go
  exercises/practice/reverse-string/reverse_string_test.go
Labels: x:rep/small

#2358 rectangles: updated exercise generator to new test generator
  exercises/practice/rectangles/.docs/instructions.md
  exercises/practice/rectangles/.meta/config.json
  exercises/practice/rectangles/.meta/gen.go
  exercises/practice/rectangles/.meta/tests.toml
  exercises/practice/rectangles/cases_test.go
  exercises/practice/rectangles/rectangles_test.go
Labels: status/awaiting-contributor, x:rep/small

#2360 Small fixes to need-for-speed exercise
  exercises/concept/need-for-speed/.docs/hints.md
  exercises/concept/need-for-speed/.docs/instructions.md
  exercises/concept/need-for-speed/.meta/exemplar.go
  exercises/concept/need-for-speed/need_for_speed.go
Labels: status/awaiting-contributor, x:rep/small

#2366 run-length-encoding: updated exercise generator to new test generator
  exercises/practice/run-length-encoding/.meta/config.json
  exercises/practice/run-length-encoding/.meta/gen.go
  exercises/practice/run-length-encoding/cases_test.go
  exercises/practice/run-length-encoding/run_length_encoding_test.go
Labels: x:rep/small

#2367 say: updated exercise generator to new test generator
  exercises/practice/say/.meta/config.json
  exercises/practice/say/.meta/gen.go
  exercises/practice/say/cases_test.go
  exercises/practice/say/say_test.go
Labels: x:rep/small

#2368 scale-generator: updated exercise generator to new test generator
  exercises/practice/scale-generator/.docs/instructions.md
  exercises/practice/scale-generator/.meta/config.json
  exercises/practice/scale-generator/.meta/example.go
  exercises/practice/scale-generator/.meta/gen.go
  exercises/practice/scale-generator/.meta/tests.toml
  exercises/practice/scale-generator/cases_test.go
  exercises/practice/scale-generator/scale_generator_test.go
Labels: x:rep/small

#2373 space-age: updated exercise generator to new test generator
  exercises/practice/space-age/.docs/instructions.append.md
  exercises/practice/space-age/.meta/config.json
  exercises/practice/space-age/.meta/example.go
  exercises/practice/space-age/.meta/gen.go
  exercises/practice/space-age/.meta/tests.toml
  exercises/practice/space-age/cases_test.go
  exercises/practice/space-age/space_age_test.go
Labels: x:rep/small

#2377 sum-of-multiples: updated exercise generator to new test generator
  exercises/practice/sum-of-multiples/.meta/config.json
  exercises/practice/sum-of-multiples/.meta/gen.go
  exercises/practice/sum-of-multiples/cases_test.go
  exercises/practice/sum-of-multiples/sum_of_multiples_test.go
Labels: x:rep/small

#2378 transpose: updated exercise generator to new test generator
  exercises/practice/transpose/.meta/config.json
  exercises/practice/transpose/.meta/gen.go
  exercises/practice/transpose/.meta/tests.toml
  exercises/practice/transpose/cases_test.go
  exercises/practice/transpose/transpose_test.go
Labels: x:rep/small

#2381 variable-length-quantity: updated exercise generator to new test gene…
  exercises/practice/variable-length-quantity/.docs/instructions.md
  exercises/practice/variable-length-quantity/.meta/config.json
  exercises/practice/variable-length-quantity/.meta/gen.go
  exercises/practice/variable-length-quantity/cases_test.go
  exercises/practice/variable-length-quantity/variable_length_quantity_test.go
Labels: x:rep/small

#2383 word-search: updated exercise generator to new test generator
  exercises/practice/word-search/.meta/config.json
  exercises/practice/word-search/.meta/gen.go
  exercises/practice/word-search/.meta/tests.toml
  exercises/practice/word-search/cases_test.go
  exercises/practice/word-search/word_search_test.go
Labels: x:rep/small

#2385 yacht: updated exercise generator to new test generator
  exercises/practice/yacht/.docs/instructions.md
  exercises/practice/yacht/.meta/config.json
  exercises/practice/yacht/.meta/gen.go
  exercises/practice/yacht/yacht_test.go
Labels: x:rep/small

#2363 added the edge test case for `YearsBeforeDesiredBalance()`
  exercises/concept/interest-is-interesting/interest_is_interesting_test.go
Labels: status/awaiting-contributor, x:rep/small

#2384 wordy: updated exercise generator to new test generator
  exercises/practice/wordy/.meta/config.json
  exercises/practice/wordy/.meta/gen.go
  exercises/practice/wordy/.meta/tests.toml
  exercises/practice/wordy/cases_test.go
  exercises/practice/wordy/wordy_test.go
Labels: status/awaiting-contributor, x:rep/small

#2382 word-count: updated exercise generator to new test generator
  exercises/practice/word-count/.meta/config.json
  exercises/practice/word-count/.meta/example.go
  exercises/practice/word-count/.meta/gen.go
  exercises/practice/word-count/.meta/tests.toml
  exercises/practice/word-count/cases_test.go
  exercises/practice/word-count/word_count_test.go
Labels: status/awaiting-contributor, x:rep/small

#2280 Changes to iterating map output.
  concepts/range-iteration/about.md
  concepts/range-iteration/introduction.md
  exercises/concept/chessboard/.docs/introduction.md
Labels: status/awaiting-contributor, x:rep/small

#2374 Update CI to run 1.18
  .github/workflows/exercise-tests.yml
  bin/fetch-golangci-lint
  exercises/practice/accumulate/accumulate_test.go
  exercises/practice/scale-generator/.meta/example.go
Labels: x:rep/small

#2388 census: add more tests for Count()
  exercises/concept/census/census_test.go
Labels: x:rep/small

#2389 meetup: revert stub to not include the solution
  exercises/practice/meetup/meetup.go
Labels: x:rep/small

#2391 [Card Tricks] add admonition
  exercises/concept/card-tricks/.docs/instructions.md
Labels: x:rep/small

#2390 markdown: adopt code to pass newly generated tests
  exercises/practice/markdown/.meta/config.json
  exercises/practice/markdown/.meta/example.go
  exercises/practice/markdown/.meta/gen.go
  exercises/practice/markdown/cases_test.go
  exercises/practice/markdown/markdown.go
  exercises/practice/markdown/markdown_test.go
Labels: x:rep/medium

#2392 proverb: adjusted difficulty to 3
  config.json
Labels: x:rep/tiny

#2393 beer-song: adjusted tests
  exercises/practice/beer-song/.meta/config.json
  exercises/practice/beer-song/beer_song_test.go
Labels: x:rep/small

#2395 Updated script run-generators
  bin/run-generators
  exercises/practice/all-your-base/.meta/gen.go
  exercises/practice/allergies/.meta/gen.go
  exercises/practice/atbash-cipher/.docs/instructions.md
  exercises/practice/bowling/.meta/config.json
  exercises/practice/bowling/.meta/tests.toml
  exercises/practice/forth/.meta/config.json
  exercises/practice/markdown/.meta/tests.toml
  exercises/practice/saddle-points/.docs/instructions.md
  exercises/practice/state-of-tic-tac-toe/.meta/config.json
  exercises/practice/state-of-tic-tac-toe/.meta/gen.go
  exercises/practice/state-of-tic-tac-toe/cases_test.go
  gen/gen.go
  gen/remote.go
Labels: x:rep/medium

#2397 variable-length-quantity: fixed text
  exercises/practice/variable-length-quantity/variable_length_quantity.go
Labels: x:rep/tiny

#2398 bank-account: small fixes to instructions
  exercises/practice/bank-account/.docs/instructions.append.md
Labels: x:rep/small

#2399 need-for-speed: added test case to cover a battery level below 100% that still allows…
  exercises/concept/need-for-speed/need_for_speed_test.go
Labels: x:rep/small
