Repository exercism/go, pull requests merged in 2022-01, with the labels that each got.

#2051 Add benchmarks for `run-length-encoding` exercise
  exercises/practice/run-length-encoding/run_length_encoding_test.go
Labels: x:size/small

#2052 Update introduction.md
  concepts/basics/introduction.md
Labels: x:size/tiny

#2053 elons-toys: minor tweaks
  exercises/concept/elons-toys/.docs/instructions.md
  exercises/concept/elons-toys/.docs/introduction.md
  exercises/concept/elons-toys/elons_toys_test.go
Labels: x:size/small

#2058 Replace CamelCase with PascalCase
  concepts/basics/about.md
  exercises/concept/lasagna/.docs/introduction.md
Labels: x:size/tiny

#2057 Lasagna Master: Improve task 3 (AddSecretIngredient)
  exercises/concept/lasagna-master/.docs/hints.md
  exercises/concept/lasagna-master/.docs/instructions.md
  exercises/concept/lasagna-master/.meta/config.json
  exercises/concept/lasagna-master/.meta/exemplar.go
  exercises/concept/lasagna-master/lasagna_master_test.go
Labels: x:size/small

#2059 Add linter installation steps to README
  README.md
Labels: x:size/tiny

#2000 Remove obsolete concept
  concepts/iteration/.meta/config.json
  concepts/iteration/about.md
  concepts/iteration/introduction.md
  concepts/iteration/links.json
  config.json
Labels: x:size/small

#2062 Lasagna Master: Fix references to "array"
  exercises/concept/lasagna-master/.docs/hints.md
  exercises/concept/lasagna-master/.docs/instructions.md
Labels: x:size/small, status/awaiting-contributor

#2063 Reference correct function name
  exercises/concept/election-day/.docs/introduction.md
Labels: x:size/tiny

#2066 Remove index 2 value from example output
  concepts/slices/about.md
Labels: x:size/tiny

#1954 Add gomod-sync
  .github/workflows/gomod-sync.yml
  .gitignore
  README.md
  gomod-sync/README.md
  gomod-sync/cmd/check.go
  gomod-sync/cmd/config/load.go
  gomod-sync/cmd/config/load_test.go
  gomod-sync/cmd/config/version.go
  gomod-sync/cmd/config/version_test.go
  gomod-sync/cmd/root.go
  gomod-sync/cmd/update.go
  gomod-sync/config.json
  gomod-sync/go.mod
  gomod-sync/go.sum
  gomod-sync/gomod/find.go
  gomod-sync/gomod/find_test.go
  gomod-sync/gomod/info.go
  gomod-sync/gomod/info_test.go
  gomod-sync/gomod/version.go
  gomod-sync/gomod/version_test.go
  gomod-sync/main.go
  gomod-sync/testdata/exercise01/go.mod
  gomod-sync/testdata/exercise02/go.mod
  gomod-sync/testdata/version_config_no_exceptions.json
  gomod-sync/testdata/version_config_one_exception.json
  gomod-sync/testdata/version_config_two_exceptions.json
Labels: x:size/large

#2064 prime-factors: allow empty nil slices
  exercises/practice/prime-factors/prime_factors_test.go
Labels: x:size/tiny

#2068 Increase difficulty for parallel letter frequency
  config.json
Labels: x:size/tiny

#2069 Changed test inputs and example code for for parallel letter frequency
  exercises/practice/parallel-letter-frequency/.meta/config.json
  exercises/practice/parallel-letter-frequency/.meta/example.go
  exercises/practice/parallel-letter-frequency/parallel_letter_frequency_test.go
Labels: x:size/medium

#2072 Parallel Letter Frequency: Add hint towards benchmarks in instructions
  exercises/practice/parallel-letter-frequency/.docs/instructions.append.md
Labels: x:size/small

#2071 logs-logs-logs: Add details to docs
  concepts/runes/about.md
  concepts/runes/introduction.md
  exercises/concept/logs-logs-logs/.docs/hints.md
  exercises/concept/logs-logs-logs/.docs/introduction.md
Labels: x:size/small

#2073 Fix the type conversion example
  concepts/type-conversion/about.md
Labels: x:size/tiny

#2074 cars-assemble: Add clarification on which operator to use in link text
  exercises/concept/cars-assemble/.docs/hints.md
Labels: x:size/tiny

#2079 Modifying a test case to verify that car cannot finish the track distance
  exercises/concept/need-for-speed/need_for_speed_test.go
Labels: x:size/small

#2082 the-farm: fixes typo in one of the test descriptions
  exercises/concept/the-farm/the_farm_test.go
Labels: x:size/tiny
