Repository exercism/go, pull requests merged in 2022-09, with the labels that each got.

#2454 Tracks / Go / Exercises / Lasagna Master / Updated instructions.md
  exercises/concept/lasagna-master/.docs/instructions.md
Labels: x:rep/tiny

#2459 Fix 'constant' typo
  concepts/stringers/about.md
  concepts/stringers/introduction.md
  exercises/concept/meteorology/.docs/introduction.md
Labels: x:rep/tiny

#2452 Exercise grep : fix test case which incorrectly fails on nil slice, but expect empty slice
  exercises/practice/grep/grep_test.go
Labels: x:rep/small

#2487 Issue# 2484 - Added 1 to the waiting time
  exercises/concept/animal-magic/animal_magic_test.go
Labels: x:rep/small

#2485 Update hints.md
  exercises/concept/gross-store/.docs/hints.md
Labels: x:rep/tiny

#2476 Issue 2475 roman numerals max 3999
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.meta/example.go
  exercises/practice/roman-numerals/.meta/tests.toml
  exercises/practice/roman-numerals/cases_test.go
  exercises/practice/roman-numerals/roman_numerals_test.go
Labels: x:rep/small

#2461 added usage of subtests for pythagorean-triplet
  exercises/practice/pythagorean-triplet/.meta/config.json
  exercises/practice/pythagorean-triplet/pythagorean_triplet_test.go
Labels: x:rep/small

#2462 Updated link in docs/ABOUT.md
  docs/ABOUT.md
Labels: x:rep/small

#2466 added usage of subtests for spiral-matrix
  exercises/practice/spiral-matrix/.meta/config.json
  exercises/practice/spiral-matrix/spiral_matrix_test.go
Labels: x:rep/small

#2445 Add test case for non-ascii anagrams
  exercises/practice/anagram/.meta/gen.go
  exercises/practice/anagram/anagram_test.go
  exercises/practice/anagram/cases_test.go
Labels: x:rep/small

#2474 update code block for direct execution
  exercises/concept/elons-toys/.docs/introduction.md
Labels: status/awaiting-contributor, x:rep/small

#2463 added usage of subtests for queen-attack
  exercises/practice/queen-attack/.meta/config.json
  exercises/practice/queen-attack/queen_attack_test.go
Labels: status/awaiting-contributor, x:rep/small

#2460 added usage of subtest for protein-translation
  exercises/practice/protein-translation/.meta/config.json
  exercises/practice/protein-translation/protein_translation_detailed_test.go
  exercises/practice/protein-translation/protein_translation_test.go
Labels: status/awaiting-contributor, x:rep/small

#2493 Remove the stale bot
  .github/workflows/stale-contributor.yml
  .github/workflows/stale-maintainer.yml
Labels: x:rep/small

#2469 added usage of subtests for triangle
  exercises/practice/triangle/.meta/config.json
  exercises/practice/triangle/triangle_test.go
Labels: x:rep/small

#2455 added usage of subtests and added descriptions for ocr-numbers
  exercises/practice/ocr-numbers/.meta/config.json
  exercises/practice/ocr-numbers/ocr_numbers_test.go
Labels: x:rep/small

#2456 added usage of subtests for palindrome-products
  exercises/practice/palindrome-products/.meta/config.json
  exercises/practice/palindrome-products/palindrome_products_test.go
Labels: x:rep/small

#2457 added usage of subtests for exercise pascals-triangle
  exercises/practice/pascals-triangle/.meta/config.json
  exercises/practice/pascals-triangle/pascals_triangle_test.go
Labels: x:rep/small

#2465 added usage of subtests for series
  exercises/practice/series/.meta/config.json
  exercises/practice/series/asktoomuch_test.go
  exercises/practice/series/first_test.go
  exercises/practice/series/series_test.go
Labels: x:rep/small

#2441 Added Additional Hint for Processing Parts of a Date
  exercises/concept/booking-up-for-beauty/.docs/hints.md
Labels: x:size/small

#2488 Flatten Array - Improve error message for nil slice
  exercises/practice/flatten-array/flatten_array_test.go
Labels: status/awaiting-contributor, x:rep/small

#2278 Update about.md in About Slices concept
  concepts/slices/about.md
  concepts/slices/introduction.md
  exercises/concept/card-tricks/.docs/introduction.md
Labels: status/awaiting-contributor, x:rep/small

#2414 Added exercise complex-numbers for Golang track
  config.json
  exercises/practice/complex-numbers/.docs/instructions.md
  exercises/practice/complex-numbers/.meta/config.json
  exercises/practice/complex-numbers/.meta/example.go
  exercises/practice/complex-numbers/.meta/gen.go
  exercises/practice/complex-numbers/.meta/tests.toml
  exercises/practice/complex-numbers/cases_test.go
  exercises/practice/complex-numbers/complex_numbers.go
  exercises/practice/complex-numbers/complex_numbers_test.go
  exercises/practice/complex-numbers/go.mod
Labels: x:rep/large

#2498 Sieve: Fix empty slice test
  exercises/practice/sieve/sieve_test.go
Labels: x:rep/small

#2500 Update test dependencies and docs
  README.md
  bin/fetch-golangci-lint
Labels: x:rep/small

#2501 Saddle Points: Remove inconsistent instructions from test file - Fixes #2482
  exercises/practice/saddle-points/saddle_points_test.go
Labels: x:rep/small
