Repository exercism/go, pull requests merged in 2022-10, with the labels that each got.

#2507 Triangle: fix KindsNotEqual test case
  exercises/practice/triangle/triangle_test.go
Labels: hacktoberfest-accepted, x:rep/small

#2509 Say: implement new tests
  exercises/practice/say/.meta/tests.toml
  exercises/practice/say/cases_test.go
Labels: hacktoberfest-accepted, x:rep/small

#2512 Normalize practice exercise names
  config.json
Labels: x:rep/small

#2514 Fix a typo in the last task's title ("MetData")
  exercises/concept/meteorology/.docs/instructions.md
Labels: hacktoberfest-accepted, x:rep/tiny

#2520 removed unnecesary line of example code in Meteorology exercise
  exercises/concept/meteorology/.docs/instructions.md
Labels: hacktoberfest-accepted, x:rep/tiny

#2515 Deprecate beer-song and add bottle-song
  config.json
  exercises/practice/bottle-song/.docs/instructions.md
  exercises/practice/bottle-song/.meta/config.json
  exercises/practice/bottle-song/.meta/example.go
  exercises/practice/bottle-song/.meta/gen.go
  exercises/practice/bottle-song/.meta/tests.toml
  exercises/practice/bottle-song/bottle_song.go
  exercises/practice/bottle-song/bottle_song_test.go
  exercises/practice/bottle-song/cases_test.go
  exercises/practice/bottle-song/go.mod
Labels: hacktoberfest-accepted, x:rep/medium

#2521 Remove gitter references and use forum
  README.md
Labels: hacktoberfest-accepted, x:rep/tiny

#2523 Update function signatures provided in matrix exercise
  exercises/practice/matrix/.meta/example.go
  exercises/practice/matrix/matrix.go
  exercises/practice/matrix/matrix_test.go
Labels: hacktoberfest-accepted, x:rep/medium

#2522 Make "complex-numbers" package name not be the same as a builtin
  exercises/practice/complex-numbers/.meta/example.go
  exercises/practice/complex-numbers/.meta/gen.go
  exercises/practice/complex-numbers/cases_test.go
  exercises/practice/complex-numbers/complex_numbers.go
  exercises/practice/complex-numbers/complex_numbers_test.go
Labels: hacktoberfest-accepted, x:rep/small

#2525 Bring instruction into line with stub file
  exercises/practice/error-handling/.docs/instructions.md
Labels: hacktoberfest-accepted, x:rep/tiny

#2526 sublist: Fixes sublist exercise by adding missing Relation type.
  exercises/practice/sublist/.meta/config.json
  exercises/practice/sublist/.meta/example.go
  exercises/practice/sublist/relations.go
  exercises/practice/sublist/sublist.go
Labels: hacktoberfest-accepted, x:rep/small
