Repository exercism/go, pull requests merged in 2022-05, with the labels that each got.

#2210 Fixes #2105: Need for Speed - Clarify instruction text on distance & battery condition
  exercises/concept/need-for-speed/.docs/instructions.md
Labels: x:rep/small

#2209 Fixed "Output" - Expenses exercise
  exercises/concept/expenses/.docs/instructions.md
  exercises/concept/expenses/.docs/introduction.md
Labels: x:size/small

#2218 Update instructions.md
  exercises/concept/the-farm/.docs/instructions.md
Labels: x:size/small

#2220 Fix typo in slices and maps paragraph
  concepts/pointers/about.md
  concepts/pointers/introduction.md
  exercises/concept/election-day/.docs/introduction.md
Labels: x:size/small

#2225 Improve exercise nth-prime
  exercises/practice/nth-prime/.docs/instructions.append.md
  exercises/practice/nth-prime/.meta/config.json
  exercises/practice/nth-prime/.meta/example.go
  exercises/practice/nth-prime/.meta/gen.go
  exercises/practice/nth-prime/cases_test.go
  exercises/practice/nth-prime/nth_prime.go
  exercises/practice/nth-prime/nth_prime_test.go
Labels: x:size/medium, status/awaiting-contributor

#2208 Concept stringers with exercise
  concepts/stringers/.meta/config.json
  concepts/stringers/about.md
  concepts/stringers/introduction.md
  concepts/stringers/links.json
  config.json
  exercises/concept/meteorology/.docs/hints.md
  exercises/concept/meteorology/.docs/instructions.md
  exercises/concept/meteorology/.docs/introduction.md
  exercises/concept/meteorology/.meta/config.json
  exercises/concept/meteorology/.meta/design.md
  exercises/concept/meteorology/.meta/exemplar.go
  exercises/concept/meteorology/go.mod
  exercises/concept/meteorology/meteorology.go
  exercises/concept/meteorology/meteorology_test.go
Labels: status/awaiting-contributor, x:rep/large

#2217 Tree Building: add test case
  exercises/practice/tree-building/tree_building_test.go
Labels: x:size/small, status/awaiting-contributor

#2227 Clock: Update instructions markdown links
  exercises/practice/clock/.docs/instructions.append.md
Labels: x:size/small, status/awaiting-contributor
