Repository exercism/go, pull requests merged in 2023-09, with the labels that each got.

#2694 Sync docs where the changes are minor
  exercises/practice/list-ops/.docs/instructions.md
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/secret-handshake/.meta/config.json
Labels: x:rep/small

#2700 Update test order within gross_store_test.go to match order of steps
  exercises/concept/gross-store/gross_store_test.go
Labels: x:rep/small

#2698 Fix godoc comment variable name
  exercises/concept/election-day/.docs/instructions.md
  exercises/concept/election-day/election_result.go
Labels: x:rep/tiny

#2701 Change strain to use generics
  config.json
  exercises/practice/strain/.meta/config.json
  exercises/practice/strain/.meta/example.go
  exercises/practice/strain/.meta/tests.toml
  exercises/practice/strain/strain.go
  exercises/practice/strain/strain_test.go
Labels: x:rep/medium

#2712 Convert backtick (`) admonition fences to tildes (~)
  concepts/variadic-functions/about.md
  concepts/variadic-functions/introduction.md
  exercises/concept/card-tricks/.docs/introduction.md
  exercises/practice/bob/.approaches/if-statements/content.md
  exercises/practice/bob/.approaches/switch-statement/content.md
  exercises/practice/clock/.approaches/clock-as-int/content.md
  exercises/practice/grains/.approaches/bit-shifting/content.md
  exercises/practice/isogram/.approaches/map/content.md
  exercises/practice/pig-latin/.approaches/map-lookups-with-generics/content.md
  exercises/practice/protein-translation/.approaches/map/content.md
  exercises/practice/protein-translation/.approaches/switch/content.md
  exercises/practice/rna-transcription/.approaches/map-object/content.md
  exercises/practice/strain/.approaches/using-generics/content.md
Labels: x:size/tiny
