Repository exercism/go, pull requests merged in 2023-02, with the labels that each got.

#2594 Fix typos in introduction.md
  concepts/interfaces/about.md
  concepts/interfaces/introduction.md
  exercises/concept/airport-robot/.docs/introduction.md
Labels: x:rep/small

#2598 Fix links in interface concept
  concepts/interfaces/about.md
  concepts/interfaces/introduction.md
  concepts/interfaces/links.json
  exercises/concept/airport-robot/.docs/hints.md
Labels: x:rep/small

#2599 Set icon for airport robot
  exercises/concept/airport-robot/.meta/config.json
Labels: x:rep/tiny

#2601 Set up lasagna master for test runner version 3
  exercises/concept/lasagna-master/.meta/config.json
Labels: x:rep/tiny

#2604 Enable task ids for election day
  exercises/concept/election-day/.meta/config.json
Labels: x:rep/tiny

#2605 Disable task ids
  exercises/concept/election-day/.meta/config.json
  exercises/concept/lasagna-master/.meta/config.json
Labels: x:rep/tiny

#2606 Small fixes to Airport Robot
  concepts/interfaces/about.md
  concepts/interfaces/introduction.md
  exercises/concept/airport-robot/.docs/instructions.md
  exercises/concept/airport-robot/.docs/introduction.md
Labels: x:rep/small

#2607 Typo fixes for the slices concept
  concepts/slices/about.md
  concepts/slices/introduction.md
  exercises/concept/card-tricks/.docs/introduction.md
Labels: x:rep/small

#2589 Updated the parameter in the the fucntion.
  exercises/practice/leap/leap.go
Labels: x:rep/tiny

#2590 Added extra example of NeedsLicense function.
  exercises/concept/vehicle-purchase/.docs/instructions.md
Labels: x:rep/tiny

#2608 Fix typo in time concept
  concepts/time/about.md
  concepts/time/introduction.md
  exercises/concept/booking-up-for-beauty/.docs/introduction.md
Labels: x:rep/small

#2610 Sync gigasecond docs with problem-specifications
  exercises/practice/gigasecond/.docs/instructions.md
  exercises/practice/gigasecond/.docs/introduction.md
Labels: x:rep/small

#2611 Sync bob docs with problem-specifications
  exercises/practice/bob/.docs/instructions.md
  exercises/practice/bob/.docs/introduction.md
Labels: x:rep/small

#2613 Format files with `configlet fmt`
  exercises/concept/airport-robot/.meta/config.json
Labels: x:rep/tiny

#2614 Add resistor-color practice exercise
  config.json
  exercises/practice/resistor-color/.docs/instructions.md
  exercises/practice/resistor-color/.meta/config.json
  exercises/practice/resistor-color/.meta/example.go
  exercises/practice/resistor-color/.meta/gen.go
  exercises/practice/resistor-color/.meta/tests.toml
  exercises/practice/resistor-color/cases_test.go
  exercises/practice/resistor-color/go.mod
  exercises/practice/resistor-color/resistor_color.go
  exercises/practice/resistor-color/resistor_color_test.go
Labels: x:rep/medium
