Repository exercism/go, pull requests merged in 2023-11, with the labels that each got.

#2727 CI: pin GitHub Actions runners
  .github/workflows/exercise-tests.yml
  .github/workflows/gomod-sync.yml
  .github/workflows/stub-tests.yml
Labels: x:size/tiny

#2723 fix typo and 404 links
  exercises/practice/nucleotide-count/.approaches/introduction.md
Labels: x:rep/small

#2721 Update function comment resistor_color.go
  exercises/practice/resistor-color/resistor_color.go
Labels: x:rep/tiny

#2711 Update introduction.md
  concepts/time/about.md
  concepts/time/introduction.md
  exercises/concept/booking-up-for-beauty/.docs/introduction.md
Labels: x:rep/tiny

#2726 remove double percent signs
  exercises/concept/vehicle-purchase/vehicle_purchase_test.go
Labels: x:rep/small
