Repository exercism/go, pull requests merged in 2024-01, with the labels that each got.

#2735 clock: update clock exercise instructions to point to correct receiver type documentation
  exercises/practice/clock/.docs/instructions.append.md
Labels: x:rep/tiny

#2746 Add testcase for TestCalculateResellPrice
  exercises/concept/vehicle-purchase/vehicle_purchase_test.go
Labels: x:size/small

#2747 leap: sync
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
Labels: x:size/tiny

#2748 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#2751 Remove obsolete information from Go track's Space Age exercise
  exercises/practice/space-age/.docs/instructions.append.md
Labels: x:rep/small

#2750 Nucleotide Count Excercise: Mistype fastest method according to "Performance deep dive" page
  exercises/practice/nucleotide-count/.approaches/introduction.md
Labels: x:rep/small

#2755 Exclude insecure rand sources checks
  .golangci.yml
Labels: x:rep/tiny

#2756 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
