Repository exercism/go, pull requests merged in 2024-07, with the labels that each got.

#2818 resistor-color-trio: sync
  exercises/practice/resistor-color-trio/.docs/instructions.md
Labels: x:size/tiny

#2817 resistor-color-duo: sync
  exercises/practice/resistor-color-duo/.docs/instructions.md
Labels: x:size/tiny

#2815 resistor-color: sync
  exercises/practice/resistor-color/.docs/instructions.md
Labels: x:size/tiny

#2757 Add "Knapsack" exercise
  config.json
  exercises/practice/knapsack/.docs/instructions.md
  exercises/practice/knapsack/.docs/introduction.md
  exercises/practice/knapsack/.meta/config.json
  exercises/practice/knapsack/.meta/example.go
  exercises/practice/knapsack/.meta/gen.go
  exercises/practice/knapsack/.meta/tests.toml
  exercises/practice/knapsack/cases_test.go
  exercises/practice/knapsack/go.mod
  exercises/practice/knapsack/knapsack.go
  exercises/practice/knapsack/knapsack_test.go
Labels: x:rep/large

#2797 Fix typos in regular-expressions concept instructions
  concepts/regular-expressions/introduction.md
  exercises/concept/parsing-log-files/.docs/introduction.md
Labels: x:rep/small

#2820 Add benchmark to Nucleotide Count
  exercises/practice/nucleotide-count/nucleotide_count_test.go
Labels: x:rep/small

#2766 Remove unused 'input' field
  exercises/practice/resistor-color/.meta/gen.go
  exercises/practice/resistor-color/cases_test.go
Labels: x:rep/small

#2763 card-tricks: Check if index is >= len(slice)
  exercises/concept/card-tricks/card_tricks_test.go
Labels: x:rep/small

#2773 Fix a small typo
  exercises/concept/airport-robot/airport_robot_test.go
Labels: x:rep/small

#2771 prime-factors: use slices package to sort and compare test cases
  exercises/practice/prime-factors/prime_factors_test.go
Labels: x:rep/small

#2780 bird-watcher: Add test case for a week in the end of the log
  exercises/concept/bird-watcher/bird_watcher_test.go
Labels: x:size/small

#2823 the-farm: fix small typo
  exercises/concept/the-farm/.docs/instructions.md
Labels: x:rep/tiny

#2825 Single sentence per line for Runes
  concepts/runes/about.md
  concepts/runes/introduction.md
Labels: x:rep/small

#2824 Describing a string as a sequence of runes is very confusing
  concepts/runes/about.md
  concepts/runes/introduction.md
  exercises/concept/logs-logs-logs/.docs/introduction.md
Labels: x:rep/small

#2819 Update instructions.md
  exercises/concept/weather-forecast/.docs/instructions.md
Labels: x:rep/tiny

#2821 Update introduction.md
  concepts/first-class-functions/about.md
  concepts/first-class-functions/introduction.md
  exercises/concept/expenses/.docs/introduction.md
Labels: x:rep/small

#2826 Minor correction to the Anumal magic instructions markdown file
  exercises/concept/animal-magic/.docs/instructions.md
Labels: x:rep/small
